/* generated by build_site.py — do not edit by hand */
window.APP = {
 "buildDate": "September 15, 2026",
 "taxonomy": [
  "LLM / Foundation Model",
  "ERP",
  "CRM",
  "ITSM / Workflow",
  "System Integrator",
  "Consulting / Advisory",
  "Managed Services",
  "Data Platform",
  "Analytics & BI",
  "Cybersecurity",
  "Physical / Industrial AI",
  "Digital Twin",
  "Engineering Software",
  "Cloud & Infrastructure",
  "Automation / RPA",
  "Semiconductors / Compute",
  "Content & Marketing"
 ],
 "vendors": [
  {
   "slug": "accenture",
   "name": "Accenture",
   "website": "https://www.accenture.com",
   "linkedin": "https://www.linkedin.com/company/accenture",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Consulting / Advisory",
    "Managed Services"
   ],
   "description": "The scale player in technology services: ~799,000 people, $69.7B of FY2025 revenue, and $80.6B of new bookings. It has partnered with 195 of its top 200 clients for ten years or more, which makes it the default incumbent inside most large enterprises rather than a challenger.",
   "revenue": "$69.7B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "accenture-dashboard.html",
   "pdf": "accenture-one-sheet.pdf",
   "people": [
    {
     "name": "Julie Sweet",
     "title": "Chair & Chief Executive Officer",
     "href": "person-accenture-julie-sweet.html",
     "id": "accenture-julie-sweet",
     "researched": true
    },
    {
     "name": "Karthik Narain",
     "title": "Group Chief Executive, Technology & Chief Technology Officer",
     "href": "person-accenture-karthik-narain.html",
     "id": "accenture-karthik-narain",
     "researched": true
    },
    {
     "name": "John Walsh",
     "title": "Chief Operating Officer",
     "href": "person-accenture-john-walsh.html",
     "id": "accenture-john-walsh",
     "researched": true
    }
   ]
  },
  {
   "slug": "adobe",
   "name": "Adobe",
   "website": "https://www.adobe.com",
   "linkedin": "https://www.linkedin.com/company/adobe",
   "group": "Enterprise software",
   "tags": [
    "Content & Marketing"
   ],
   "description": "The incumbent in creative software, now in the awkward position of being both an AI winner and an AI disruption target. AI-influenced ARR passed $5B in FY2025 — over a third of the total base — while the market prices the stock at a decade-low forward multiple on the view that generative tools will erode the moat.",
   "revenue": "$23.8B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "adobe-dashboard.html",
   "pdf": "adobe-one-sheet.pdf",
   "people": [
    {
     "name": "Shantanu Narayen",
     "title": "Chair & Chief Executive Officer (transitioning — see note)",
     "href": "person-adobe-shantanu-narayen.html",
     "id": "adobe-shantanu-narayen",
     "researched": true
    }
   ]
  },
  {
   "slug": "aws",
   "name": "Amazon Web Services",
   "website": "https://aws.amazon.com",
   "linkedin": "https://www.linkedin.com/company/amazon-web-services",
   "group": "Frontier AI / LLM",
   "tags": [
    "Cloud & Infrastructure",
    "LLM / Foundation Model",
    "Data Platform"
   ],
   "description": "Holds about 28% of global cloud infrastructure against Azure's 21% and Google Cloud's 14%. The structural story is vertical integration: custom chips built over a decade now carry the majority of Bedrock inference, which converts directly into margin and price advantage as workloads shift from training to inference.",
   "revenue": "~$150B (annualised)",
   "status": "full",
   "hasPdf": false,
   "dash": "aws-dashboard.html",
   "pdf": "aws-one-sheet.pdf",
   "people": [
    {
     "name": "Matt Garman",
     "title": "Chief Executive Officer, AWS",
     "href": "person-aws-matt-garman.html",
     "id": "aws-matt-garman",
     "researched": true
    },
    {
     "name": "Andy Jassy",
     "title": "President & Chief Executive Officer, Amazon (AWS founder)",
     "href": "person-aws-andy-jassy.html",
     "id": "aws-andy-jassy",
     "researched": true
    }
   ]
  },
  {
   "slug": "anthropic",
   "name": "Anthropic",
   "website": "https://www.anthropic.com",
   "linkedin": "https://www.linkedin.com/company/anthropicresearch",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model"
   ],
   "description": "Went from about $1B to $47B of annualised revenue in seventeen months, overtaking OpenAI on revenue in April 2026 and on valuation in May. Roughly 80% of revenue comes from business and API customers rather than consumers, which is the deliberate strategic choice behind the ramp.",
   "revenue": "$47B (May 2026)",
   "status": "full",
   "hasPdf": false,
   "dash": "anthropic-dashboard.html",
   "pdf": "anthropic-one-sheet.pdf",
   "people": [
    {
     "name": "Dario Amodei",
     "title": "Co-Founder & Chief Executive Officer",
     "href": "person-anthropic-dario-amodei.html",
     "id": "anthropic-dario-amodei",
     "researched": true
    },
    {
     "name": "Daniela Amodei",
     "title": "Co-Founder & President",
     "href": "person-anthropic-daniela-amodei.html",
     "id": "anthropic-daniela-amodei",
     "researched": true
    },
    {
     "name": "Krishna Rao",
     "title": "Chief Financial Officer",
     "href": "person-anthropic-krishna-rao.html",
     "id": "anthropic-krishna-rao",
     "researched": true
    }
   ]
  },
  {
   "slug": "aveva",
   "name": "AVEVA",
   "website": "https://www.aveva.com",
   "linkedin": "https://www.linkedin.com/company/aveva",
   "group": "Physical / Industrial AI",
   "tags": [
    "Engineering Software",
    "Digital Twin",
    "Physical / Industrial AI"
   ],
   "description": "No longer an independent company to evaluate on its own financials — AVEVA is now the industrial-software arm of Schneider Electric, and is about to absorb Cognite too, becoming the most consolidated platform on this list.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": true,
   "dash": "aveva-dashboard.html",
   "pdf": "aveva-one-sheet.pdf",
   "people": [
    {
     "name": "Caspar Herzberg",
     "title": "Chief Executive Officer",
     "href": "person-aveva-caspar-herzberg.html",
     "id": "aveva-caspar-herzberg",
     "researched": true
    },
    {
     "name": "Peter Herweck",
     "title": "Chairperson (former CEO, Schneider Electric)",
     "href": "person-aveva-peter-herweck.html",
     "id": "aveva-peter-herweck",
     "researched": true
    }
   ]
  },
  {
   "slug": "aziro",
   "name": "Aziro",
   "website": "https://www.aziro.com/en",
   "linkedin": "https://www.linkedin.com/company/azirotech",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "A niche engineering partner rather than a scale integrator — roughly 1,200 people against Accenture's 799,000. Its stated focus is product engineering for enterprises, high-growth ISVs and AI-first companies, with storage, infrastructure and QA as the historical strengths carried over from the MSys years.",
   "revenue": "~$292M (unverified)",
   "status": "full",
   "hasPdf": false,
   "dash": "aziro-dashboard.html",
   "pdf": "aziro-one-sheet.pdf",
   "people": [
    {
     "name": "Sanjay Sehgal",
     "title": "Founder, Chairman & Chief Executive Officer",
     "href": "person-aziro-sanjay-sehgal.html",
     "id": "aziro-sanjay-sehgal",
     "researched": true
    }
   ]
  },
  {
   "slug": "bain",
   "name": "Bain & Company",
   "website": "https://www.bain.com",
   "linkedin": "https://www.linkedin.com/company/bain-and-company",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory"
   ],
   "description": "One of the three strategy firms, and the one with the deepest private equity franchise — which makes it the most likely of the MBB set to already be inside GIP's diligence workflows. It is also the least transparent: it stopped publishing revenue and uses at least two inconsistent headcount methodologies.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": false,
   "dash": "bain-dashboard.html",
   "pdf": "bain-one-sheet.pdf",
   "people": [
    {
     "name": "Christophe De Vusser",
     "title": "Worldwide Managing Partner, CEO & Chairman of the Board",
     "href": "person-bain-christophe-de-vusser.html",
     "id": "bain-christophe-de-vusser",
     "researched": true
    },
    {
     "name": "Manny Maceda",
     "title": "Chair",
     "href": "person-bain-manny-maceda.html",
     "id": "bain-manny-maceda",
     "researched": true
    },
    {
     "name": "Orit Gadiesh",
     "title": "Chair Emeritus",
     "href": "person-bain-orit-gadiesh.html",
     "id": "bain-orit-gadiesh",
     "researched": true
    }
   ]
  },
  {
   "slug": "bentley-systems",
   "name": "Bentley Systems",
   "website": "https://www.bentley.com",
   "linkedin": "https://www.linkedin.com/company/bentley-systems",
   "group": "Physical / Industrial AI",
   "tags": [
    "Engineering Software",
    "Digital Twin"
   ],
   "description": "Profitable, public infrastructure-software incumbent with a 40-year design-through-operations footprint — the closest thing to an “establishment” peer for Sand's water/energy/transport verticals, and the best-rated employer on this list by its own staff.",
   "revenue": "$1.5B (FY2025)",
   "status": "full",
   "hasPdf": true,
   "dash": "bentley-systems-dashboard.html",
   "pdf": "bentley-systems-one-sheet.pdf",
   "people": [
    {
     "name": "Nicholas Cumins",
     "title": "Chief Executive Officer",
     "href": "person-bentley-systems-nicholas-cumins.html",
     "id": "bentley-systems-nicholas-cumins",
     "researched": true
    },
    {
     "name": "Greg Bentley",
     "title": "Executive Chairman (co-founder)",
     "href": "person-bentley-systems-greg-bentley.html",
     "id": "bentley-systems-greg-bentley",
     "researched": true
    }
   ]
  },
  {
   "slug": "booz-allen",
   "name": "Booz Allen Hamilton",
   "website": "https://www.boozallen.com",
   "linkedin": "https://www.linkedin.com/company/booz-allen-hamilton",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory",
    "System Integrator"
   ],
   "description": "The largest pure-play US government technology firm, with deeper operational experience in critical national infrastructure than any commercial consultancy. FY2026 was, in its CEO's words, the most challenging year it has faced as a public company — revenue down 6.4%, headcount down 12% — while backlog hit a record $38B.",
   "revenue": "$11.2B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "booz-allen-dashboard.html",
   "pdf": "booz-allen-one-sheet.pdf",
   "people": [
    {
     "name": "Horacio Rozanski",
     "title": "Chairman, President & Chief Executive Officer",
     "href": "person-booz-allen-horacio-rozanski.html",
     "id": "booz-allen-horacio-rozanski",
     "researched": true
    }
   ]
  },
  {
   "slug": "bcg",
   "name": "Boston Consulting Group",
   "website": "https://www.bcg.com",
   "linkedin": "https://www.linkedin.com/company/boston-consulting-group",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory"
   ],
   "description": "$14.4B of 2025 revenue across 33,500 people, with AI and technology services now over 40% of the total and AI-specific work at 25% — roughly $3.6B. It is the first of the strategy firms to publish that figure, which makes it the benchmark the others get measured against.",
   "revenue": "$14.4B (2025)",
   "status": "full",
   "hasPdf": false,
   "dash": "bcg-dashboard.html",
   "pdf": "bcg-one-sheet.pdf",
   "people": [
    {
     "name": "Christoph Schweizer",
     "title": "Chief Executive Officer",
     "href": "person-bcg-christoph-schweizer.html",
     "id": "bcg-christoph-schweizer",
     "researched": true
    },
    {
     "name": "Rich Lesser",
     "title": "Global Chair (CEO 2013–2021)",
     "href": "person-bcg-rich-lesser.html",
     "id": "bcg-rich-lesser",
     "researched": true
    }
   ]
  },
  {
   "slug": "c3ai",
   "name": "C3.ai",
   "website": "https://c3.ai",
   "linkedin": "https://www.linkedin.com/company/c3-ai",
   "group": "Physical / Industrial AI",
   "tags": [
    "Physical / Industrial AI",
    "Analytics & BI"
   ],
   "description": "Public but smaller and less differentiated than Palantir, with real recent strain: revenue growth has decelerated sharply, founder Tom Siebel resumed the CEO role in May 2026 after a health-related leadership change, and Glassdoor sentiment has fallen from 3.1 to 2.9 over the past year.",
   "revenue": "$389M (FY2025)",
   "status": "full",
   "hasPdf": true,
   "dash": "c3ai-dashboard.html",
   "pdf": "c3ai-one-sheet.pdf",
   "people": [
    {
     "name": "Thomas M. Siebel",
     "title": "Founder, Chairman & Chief Executive Officer",
     "href": "person-c3ai-thomas-m-siebel.html",
     "id": "c3ai-thomas-m-siebel",
     "researched": true
    },
    {
     "name": "Stephen Ehikian",
     "title": "President",
     "href": "person-c3ai-stephen-ehikian.html",
     "id": "c3ai-stephen-ehikian",
     "researched": true
    },
    {
     "name": "Edward Abbo",
     "title": "Chief Technology Officer",
     "href": "person-c3ai-edward-abbo.html",
     "id": "c3ai-edward-abbo",
     "researched": true
    }
   ]
  },
  {
   "slug": "capgemini",
   "name": "Capgemini",
   "website": "https://www.capgemini.com",
   "linkedin": "https://www.linkedin.com/company/capgemini",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Consulting / Advisory",
    "Managed Services"
   ],
   "description": "The largest European-headquartered integrator, and the one in this set with the most credible physical-engineering capability through Capgemini Engineering. 2025 was a year of aggressive reshaping: €3.8B deployed on acquisitions, headcount up 24%, and a €700M restructuring programme announced to reorganise the workforce around AI.",
   "revenue": "€22.5B (2025)",
   "status": "full",
   "hasPdf": false,
   "dash": "capgemini-dashboard.html",
   "pdf": "capgemini-one-sheet.pdf",
   "people": [
    {
     "name": "Aiman Ezzat",
     "title": "Chief Executive Officer",
     "href": "person-capgemini-aiman-ezzat.html",
     "id": "capgemini-aiman-ezzat",
     "researched": true
    },
    {
     "name": "Nive Bhagat",
     "title": "Chief Financial Officer",
     "href": "person-capgemini-nive-bhagat.html",
     "id": "capgemini-nive-bhagat",
     "researched": true
    },
    {
     "name": "Paul Hermelin",
     "title": "Chairman of the Board",
     "href": "person-capgemini-paul-hermelin.html",
     "id": "capgemini-paul-hermelin",
     "researched": true
    }
   ]
  },
  {
   "slug": "cognite",
   "name": "Cognite",
   "website": "https://www.cognite.com",
   "linkedin": "https://www.linkedin.com/company/cognitedata",
   "group": "Physical / Industrial AI",
   "tags": [
    "Physical / Industrial AI",
    "Digital Twin",
    "Data Platform"
   ],
   "description": "The clearest signal of where this market is heading: an independent industrial-AI platform just sold to a strategic incumbent (Schneider Electric) for 18x revenue, consolidating into AVEVA.",
   "revenue": "$170M+ (2025)",
   "status": "full",
   "hasPdf": true,
   "dash": "cognite-dashboard.html",
   "pdf": "cognite-one-sheet.pdf",
   "people": [
    {
     "name": "Girish Rishi",
     "title": "Chairman & Chief Executive Officer",
     "href": "person-cognite-girish-rishi.html",
     "id": "cognite-girish-rishi",
     "researched": true
    },
    {
     "name": "John Markus Lervik",
     "title": "Co-Founder & Chief Strategy Officer",
     "href": "person-cognite-john-markus-lervik.html",
     "id": "cognite-john-markus-lervik",
     "researched": true
    },
    {
     "name": "Geir Engdahl",
     "title": "Co-Founder & Chief Technology Officer, AI",
     "href": "person-cognite-geir-engdahl.html",
     "id": "cognite-geir-engdahl",
     "researched": true
    }
   ]
  },
  {
   "slug": "cognizant",
   "name": "Cognizant",
   "website": "https://www.cognizant.com",
   "linkedin": "https://www.linkedin.com/company/cognizant",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "Returned to what it calls the industry's winner's circle two years ahead of the target set at its Investor Day, on 7% revenue growth and 140 basis points of margin expansion. 28 large deals were signed in 2025 with total contract value up nearly 50% year over year.",
   "revenue": "$21.1B (2025)",
   "status": "full",
   "hasPdf": false,
   "dash": "cognizant-dashboard.html",
   "pdf": "cognizant-one-sheet.pdf",
   "people": [
    {
     "name": "Ravi Kumar S",
     "title": "Chief Executive Officer",
     "href": "person-cognizant-ravi-kumar-s.html",
     "id": "cognizant-ravi-kumar-s",
     "researched": true
    },
    {
     "name": "Jatin Dalal",
     "title": "Chief Financial Officer",
     "href": "person-cognizant-jatin-dalal.html",
     "id": "cognizant-jatin-dalal",
     "researched": true
    }
   ]
  },
  {
   "slug": "crowdstrike",
   "name": "CrowdStrike",
   "website": "https://www.crowdstrike.com",
   "linkedin": "https://www.linkedin.com/company/crowdstrike",
   "group": "Cybersecurity",
   "tags": [
    "Cybersecurity"
   ],
   "description": "Reached $5.25B of ending ARR in FY2026 — the fastest and only pure-play cybersecurity software company to do so — while expanding non-GAAP operating margin by 370 basis points. Kurtz frames the market as consolidating onto Falcon as the operating system of cybersecurity for the agentic AI era.",
   "revenue": "$5.25B ARR (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "crowdstrike-dashboard.html",
   "pdf": "crowdstrike-one-sheet.pdf",
   "people": [
    {
     "name": "George Kurtz",
     "title": "Founder & Chief Executive Officer",
     "href": "person-crowdstrike-george-kurtz.html",
     "id": "crowdstrike-george-kurtz",
     "researched": true
    },
    {
     "name": "Burt Podbere",
     "title": "Chief Financial Officer",
     "href": "person-crowdstrike-burt-podbere.html",
     "id": "crowdstrike-burt-podbere",
     "researched": true
    }
   ]
  },
  {
   "slug": "databricks",
   "name": "Databricks",
   "website": "https://www.databricks.com",
   "linkedin": "https://www.linkedin.com/company/databricks",
   "group": "Data platform",
   "tags": [
    "Data Platform",
    "Analytics & BI"
   ],
   "description": "Grew from a $5.4B run rate in February 2026 to $7B by Q2, at over 80% growth, and raised $5B at a $190B valuation in August 2026 despite being cash-flow positive. The core data warehouse alone is $1.5B of run rate still growing at 100%.",
   "revenue": "$7B (run rate)",
   "status": "full",
   "hasPdf": false,
   "dash": "databricks-dashboard.html",
   "pdf": "databricks-one-sheet.pdf",
   "people": [
    {
     "name": "Ali Ghodsi",
     "title": "Co-Founder & Chief Executive Officer",
     "href": "person-databricks-ali-ghodsi.html",
     "id": "databricks-ali-ghodsi",
     "researched": true
    },
    {
     "name": "Matei Zaharia",
     "title": "Co-Founder & Chief Technology Officer",
     "href": "person-databricks-matei-zaharia.html",
     "id": "databricks-matei-zaharia",
     "researched": true
    }
   ]
  },
  {
   "slug": "deloitte",
   "name": "Deloitte",
   "website": "https://www.deloitte.com",
   "linkedin": "https://www.linkedin.com/company/deloitte",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory",
    "System Integrator"
   ],
   "description": "The largest firm in this set by revenue and headcount, and the first professional services firm ever to pass $70B. It has committed $3B through FY2030 to generative and agentic AI, and is unusual among the Big Four in building a product business (Zora AI) rather than only a services practice.",
   "revenue": "$70.5B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "deloitte-dashboard.html",
   "pdf": "deloitte-one-sheet.pdf",
   "people": [
    {
     "name": "Joe Ucuzoglu",
     "title": "Global Chief Executive Officer",
     "href": "person-deloitte-joe-ucuzoglu.html",
     "id": "deloitte-joe-ucuzoglu",
     "researched": true
    }
   ]
  },
  {
   "slug": "dxc",
   "name": "DXC Technology",
   "website": "https://dxc.com",
   "linkedin": "https://www.linkedin.com/company/dxctechnology",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "The smallest and weakest-performing of the large integrators tracked here. Revenue has declined organically in every quarter of FY2026 and Q4 EBIT turned negative at -$39M. What it does have is deep ownership of client legacy estate — including the Hogan core banking code — which it is trying to monetise through AI-fronted interfaces rather than replacement.",
   "revenue": "~$12.6B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "dxc-dashboard.html",
   "pdf": "dxc-one-sheet.pdf",
   "people": [
    {
     "name": "Raul Fernandez",
     "title": "President & Chief Executive Officer",
     "href": "person-dxc-raul-fernandez.html",
     "id": "dxc-raul-fernandez",
     "researched": true
    },
    {
     "name": "David Herzog",
     "title": "Chairman of the Board",
     "href": "person-dxc-david-herzog.html",
     "id": "dxc-david-herzog",
     "researched": true
    }
   ]
  },
  {
   "slug": "ey",
   "name": "EY",
   "website": "https://www.ey.com",
   "linkedin": "https://www.linkedin.com/company/ernstandyoung",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory",
    "System Integrator"
   ],
   "description": "The third-largest Big Four network by revenue, and the one with the most distinctive AI operating model. Truncale, the first woman to lead a Big Four firm, runs a Client Zero approach — EY applies AI to its own processes first, then sells the learnings. AI-related revenue grew 30% in FY2025.",
   "revenue": "$53.2B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "ey-dashboard.html",
   "pdf": "ey-one-sheet.pdf",
   "people": [
    {
     "name": "Janet Truncale",
     "title": "Global Chair & Chief Executive Officer",
     "href": "person-ey-janet-truncale.html",
     "id": "ey-janet-truncale",
     "researched": true
    }
   ]
  },
  {
   "slug": "google",
   "name": "Google",
   "website": "https://cloud.google.com",
   "linkedin": "https://www.linkedin.com/company/google",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model",
    "Cloud & Infrastructure",
    "Analytics & BI"
   ],
   "description": "Google Cloud accelerated from 48% growth in Q4 2025 to 63% in Q1 2026 to 82% in Q2, with backlog reaching $514B. Gemini processes roughly 22 billion tokens per minute through direct API use, and nearly 90% of the Fortune 100 use Gemini Enterprise.",
   "revenue": "$24.8B/qtr (Cloud)",
   "status": "full",
   "hasPdf": false,
   "dash": "google-dashboard.html",
   "pdf": "google-one-sheet.pdf",
   "people": [
    {
     "name": "Sundar Pichai",
     "title": "Chief Executive Officer, Alphabet & Google",
     "href": "person-google-sundar-pichai.html",
     "id": "google-sundar-pichai",
     "researched": true
    },
    {
     "name": "Thomas Kurian",
     "title": "Chief Executive Officer, Google Cloud",
     "href": "person-google-thomas-kurian.html",
     "id": "google-thomas-kurian",
     "researched": true
    }
   ]
  },
  {
   "slug": "hcltech",
   "name": "HCLTech",
   "website": "https://www.hcltech.com",
   "linkedin": "https://www.linkedin.com/company/hcltech",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "Delivered 3.9% constant-currency growth in FY2026 in what its CEO called an uncertain demand environment, with Advanced AI revenue crossing a $620M annualised run rate. The segment that stands out is Engineering and R&amp;D Services, which grew 9.8% — two and a half times the company average.",
   "revenue": "$14.7B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "hcltech-dashboard.html",
   "pdf": "hcltech-one-sheet.pdf",
   "people": [
    {
     "name": "C Vijayakumar",
     "title": "Chief Executive Officer & Managing Director",
     "href": "person-hcltech-c-vijayakumar.html",
     "id": "hcltech-c-vijayakumar",
     "researched": true
    },
    {
     "name": "Roshni Nadar Malhotra",
     "title": "Chairperson",
     "href": "person-hcltech-roshni-nadar-malhotra.html",
     "id": "hcltech-roshni-nadar-malhotra",
     "researched": true
    }
   ]
  },
  {
   "slug": "honeywell-forge",
   "name": "Honeywell Forge",
   "website": "https://www.honeywell.com/us/en/software/forge",
   "linkedin": "https://www.linkedin.com/company/honeywell",
   "group": "Physical / Industrial AI",
   "tags": [
    "Physical / Industrial AI",
    "Digital Twin"
   ],
   "description": "Currently mid-breakup: Honeywell is separating into standalone Aerospace, Automation and other businesses through 2026, which makes Forge's future scope and reporting lines a live open question — but it also has the best employee sentiment of any name on this list.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": true,
   "dash": "honeywell-forge-dashboard.html",
   "pdf": "honeywell-forge-one-sheet.pdf",
   "people": [
    {
     "name": "Vimal Kapur",
     "title": "Chairman & CEO, Honeywell",
     "href": "person-honeywell-forge-vimal-kapur.html",
     "id": "honeywell-forge-vimal-kapur",
     "researched": true
    }
   ]
  },
  {
   "slug": "ibm-consulting",
   "name": "IBM Consulting",
   "website": "https://www.ibm.com/consulting",
   "linkedin": "https://www.linkedin.com/company/ibm",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Consulting / Advisory",
    "Managed Services"
   ],
   "description": "IBM's services arm, at over $21B of 2025 revenue. It is the clearest example in this set of a consultancy restructuring its own delivery model around AI agents: Consulting Advantage lets IBM consultants build and manage agent teams, and Enterprise Advantage now sells that capability to clients.",
   "revenue": "$21B (2025)",
   "status": "full",
   "hasPdf": false,
   "dash": "ibm-consulting-dashboard.html",
   "pdf": "ibm-consulting-one-sheet.pdf",
   "people": [
    {
     "name": "Mohamad Ali",
     "title": "Senior Vice President, IBM Consulting",
     "href": "person-ibm-consulting-mohamad-ali.html",
     "id": "ibm-consulting-mohamad-ali",
     "researched": true
    },
    {
     "name": "Arvind Krishna",
     "title": "Chairman, President & Chief Executive Officer, IBM",
     "href": "person-ibm-consulting-arvind-krishna.html",
     "id": "ibm-consulting-arvind-krishna",
     "researched": true
    }
   ]
  },
  {
   "slug": "ibm-watsonx",
   "name": "IBM watsonx",
   "website": "https://www.ibm.com/watsonx",
   "linkedin": "https://www.linkedin.com/company/ibm",
   "group": "Physical / Industrial AI",
   "tags": [
    "LLM / Foundation Model",
    "Data Platform",
    "Physical / Industrial AI"
   ],
   "description": "A governance-first enterprise AI platform riding IBM's existing enterprise relationships rather than a vertical infrastructure play — the most horizontal (industry-agnostic) offering on this list.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": true,
   "dash": "ibm-watsonx-dashboard.html",
   "pdf": "ibm-watsonx-one-sheet.pdf",
   "people": [
    {
     "name": "Arvind Krishna",
     "title": "Chairman & CEO, IBM",
     "href": "person-ibm-watsonx-arvind-krishna.html",
     "id": "ibm-watsonx-arvind-krishna",
     "researched": true
    },
    {
     "name": "Rob Thomas",
     "title": "Senior VP, Software & Chief Commercial Officer",
     "href": "person-ibm-watsonx-rob-thomas.html",
     "id": "ibm-watsonx-rob-thomas",
     "researched": true
    }
   ]
  },
  {
   "slug": "infosys",
   "name": "Infosys",
   "website": "https://www.infosys.com",
   "linkedin": "https://www.linkedin.com/company/infosys",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "Crossed $20B of revenue in FY2026 on 3.1% constant-currency growth, with $14.9B of large deal wins — 28% higher than the prior year. AI revenue moved from 5.5% of total in Q3 FY2026 to 8.2% by mid-2026, the fastest ramp disclosed by any India-heritage firm tracked here.",
   "revenue": "$20.2B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "infosys-dashboard.html",
   "pdf": "infosys-one-sheet.pdf",
   "people": [
    {
     "name": "Salil Parekh",
     "title": "Chief Executive Officer & Managing Director (term ends March 2027)",
     "href": "person-infosys-salil-parekh.html",
     "id": "infosys-salil-parekh",
     "researched": true
    }
   ]
  },
  {
   "slug": "kpmg",
   "name": "KPMG",
   "website": "https://kpmg.com",
   "linkedin": "https://www.linkedin.com/company/kpmg",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory",
    "System Integrator"
   ],
   "description": "The smallest Big Four network at $39.8B, growing 5.1% in local currency — faster than Deloitte's 4.8% and EY's 4.0%, but from a materially smaller base. Growth is concentrated in tax, legal and audit; advisory, where AI work sits, grew only 2.9%.",
   "revenue": "$39.8B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "kpmg-dashboard.html",
   "pdf": "kpmg-one-sheet.pdf",
   "people": [
    {
     "name": "Bill Thomas",
     "title": "Global Chairman & Chief Executive Officer, KPMG International",
     "href": "person-kpmg-bill-thomas.html",
     "id": "kpmg-bill-thomas",
     "researched": true
    }
   ]
  },
  {
   "slug": "mckinsey",
   "name": "McKinsey & Company",
   "website": "https://www.mckinsey.com",
   "linkedin": "https://www.linkedin.com/company/mckinsey",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory"
   ],
   "description": "The most prestigious strategy firm, and the one making the most aggressive claims about restructuring itself around AI. QuantumBlack, a 1,700-person unit, now drives initiatives accounting for roughly 40% of the firm's work — while headcount has fallen more than 10% and about 10% of non-client-facing staff are being cut over 18 to 24 months.",
   "revenue": "~$16B (2023)",
   "status": "full",
   "hasPdf": false,
   "dash": "mckinsey-dashboard.html",
   "pdf": "mckinsey-one-sheet.pdf",
   "people": [
    {
     "name": "Bob Sternfels",
     "title": "Global Managing Partner",
     "href": "person-mckinsey-bob-sternfels.html",
     "id": "mckinsey-bob-sternfels",
     "researched": true
    },
    {
     "name": "Alex Singla",
     "title": "Senior Partner, Co-Lead of QuantumBlack",
     "href": "person-mckinsey-alex-singla.html",
     "id": "mckinsey-alex-singla",
     "researched": true
    }
   ]
  },
  {
   "slug": "meta",
   "name": "Meta",
   "website": "https://ai.meta.com",
   "linkedin": "https://www.linkedin.com/company/meta",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model"
   ],
   "description": "The only hyperscale AI spender whose infrastructure is almost entirely self-consumed — there is no Azure or AWS equivalent selling capacity to third parties. 2026 capital expenditure guidance has been raised three times to $135–145B, roughly double the $72.22B actually spent in 2025, while the company cuts 10% of its workforce.",
   "revenue": "$56.3B (Q1 26)",
   "status": "full",
   "hasPdf": false,
   "dash": "meta-dashboard.html",
   "pdf": "meta-one-sheet.pdf",
   "people": [
    {
     "name": "Mark Zuckerberg",
     "title": "Founder, Chairman & Chief Executive Officer",
     "href": "person-meta-mark-zuckerberg.html",
     "id": "meta-mark-zuckerberg",
     "researched": true
    },
    {
     "name": "Alexandr Wang",
     "title": "Chief AI Officer; lead of Meta Superintelligence Labs",
     "href": "person-meta-alexandr-wang.html",
     "id": "meta-alexandr-wang",
     "researched": true
    }
   ]
  },
  {
   "slug": "microsoft",
   "name": "Microsoft",
   "website": "https://www.microsoft.com",
   "linkedin": "https://www.linkedin.com/company/microsoft",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model",
    "Cloud & Infrastructure",
    "ERP",
    "Analytics & BI",
    "Cybersecurity"
   ],
   "description": "Azure crossed $100B of annual revenue for the first time in FY2026 and accelerated to 43% growth in Q4 rather than plateauing. Microsoft 365 Copilot passed 30 million paid seats, doubling in two quarters, against a commercial base of roughly 464 million seats — so penetration is still only about 6.5%.",
   "revenue": "$331.8B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "microsoft-dashboard.html",
   "pdf": "microsoft-one-sheet.pdf",
   "people": [
    {
     "name": "Satya Nadella",
     "title": "Chairman & Chief Executive Officer",
     "href": "person-microsoft-satya-nadella.html",
     "id": "microsoft-satya-nadella",
     "researched": true
    },
    {
     "name": "Amy Hood",
     "title": "Executive Vice President & Chief Financial Officer",
     "href": "person-microsoft-amy-hood.html",
     "id": "microsoft-amy-hood",
     "researched": true
    }
   ]
  },
  {
   "slug": "ntt-data",
   "name": "NTT DATA",
   "website": "https://www.nttdata.com",
   "linkedin": "https://www.linkedin.com/company/ntt-data",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "Japan's largest IT services company and, after absorbing NTT Ltd, a combined business and technology services operation of roughly $30B outside the group's domestic base. Unusually for an integrator, it sits inside a telecommunications group and carries real physical infrastructure alongside the services business.",
   "revenue": "~$42.3B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "ntt-data-dashboard.html",
   "pdf": "ntt-data-one-sheet.pdf",
   "people": [
    {
     "name": "Abhijit Dubey",
     "title": "President & Chief Executive Officer, NTT DATA, Inc.",
     "href": "person-ntt-data-abhijit-dubey.html",
     "id": "ntt-data-abhijit-dubey",
     "researched": true
    }
   ]
  },
  {
   "slug": "nvidia",
   "name": "NVIDIA",
   "website": "https://www.nvidia.com",
   "linkedin": "https://www.linkedin.com/company/nvidia",
   "group": "Frontier AI / LLM",
   "tags": [
    "Semiconductors / Compute",
    "Cloud & Infrastructure"
   ],
   "description": "FY2026 revenue of $215.9B, up 65%, with Data Center at 90% of the total. Huang has said cloud GPUs are sold out, that NVIDIA expects at least $1 trillion of cumulative Blackwell and Vera Rubin revenue through 2027, and bluntly that supply will fall short of demand.",
   "revenue": "$215.9B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "nvidia-dashboard.html",
   "pdf": "nvidia-one-sheet.pdf",
   "people": [
    {
     "name": "Jensen Huang",
     "title": "Founder & Chief Executive Officer",
     "href": "person-nvidia-jensen-huang.html",
     "id": "nvidia-jensen-huang",
     "researched": true
    }
   ]
  },
  {
   "slug": "openai",
   "name": "OpenAI",
   "website": "https://openai.com",
   "linkedin": "https://www.linkedin.com/company/openai",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model"
   ],
   "description": "The most broadly adopted AI product in the enterprise — roughly 92% of the Fortune 500 use ChatGPT and business customers passed one million in November 2025 — while carrying losses large enough that the IPO timetable has slipped from a 2026 listing toward 2027.",
   "revenue": "$40B+ (Aug 2026)",
   "status": "full",
   "hasPdf": false,
   "dash": "openai-dashboard.html",
   "pdf": "openai-one-sheet.pdf",
   "people": [
    {
     "name": "Sam Altman",
     "title": "Chief Executive Officer",
     "href": "person-openai-sam-altman.html",
     "id": "openai-sam-altman",
     "researched": true
    },
    {
     "name": "Sarah Friar",
     "title": "Chief Financial Officer",
     "href": "person-openai-sarah-friar.html",
     "id": "openai-sarah-friar",
     "researched": true
    }
   ]
  },
  {
   "slug": "oracle",
   "name": "Oracle",
   "website": "https://www.oracle.com",
   "linkedin": "https://www.linkedin.com/company/oracle",
   "group": "Enterprise software",
   "tags": [
    "ERP",
    "Cloud & Infrastructure",
    "Data Platform"
   ],
   "description": "Remaining performance obligations reached $638B at FY2026 close, up more than 6.5 times from $98B two years earlier — signed, non-cancellable contracts giving Oracle more than a decade of visibility in its infrastructure business, against $67.4B of actual annual revenue.",
   "revenue": "$67.4B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "oracle-dashboard.html",
   "pdf": "oracle-one-sheet.pdf",
   "people": [
    {
     "name": "Clay Magouyrk",
     "title": "Co-Chief Executive Officer",
     "href": "person-oracle-clay-magouyrk.html",
     "id": "oracle-clay-magouyrk",
     "researched": true
    },
    {
     "name": "Mike Sicilia",
     "title": "Co-Chief Executive Officer",
     "href": "person-oracle-mike-sicilia.html",
     "id": "oracle-mike-sicilia",
     "researched": true
    },
    {
     "name": "Larry Ellison",
     "title": "Chairman & Chief Technology Officer",
     "href": "person-oracle-larry-ellison.html",
     "id": "oracle-larry-ellison",
     "researched": true
    },
    {
     "name": "Safra Catz",
     "title": "Executive Vice Chair of the Board",
     "href": "person-oracle-safra-catz.html",
     "id": "oracle-safra-catz",
     "researched": true
    }
   ]
  },
  {
   "slug": "palantir",
   "name": "Palantir Technologies",
   "website": "https://www.palantir.com",
   "linkedin": "https://www.linkedin.com/company/palantir-technologies",
   "group": "Physical / Industrial AI",
   "tags": [
    "Physical / Industrial AI",
    "Data Platform",
    "Analytics & BI"
   ],
   "description": "The best-capitalized, fastest-growing name in this market by far — GAAP-profitable, ~56% revenue growth, and a fast-scaling “AIP Bootcamp” go-to-market motion pulling U.S. commercial revenue up over 130% YoY.",
   "revenue": "$4.48B (FY2025)",
   "status": "full",
   "hasPdf": true,
   "dash": "palantir-dashboard.html",
   "pdf": "palantir-one-sheet.pdf",
   "people": [
    {
     "name": "Alex Karp",
     "title": "Co-Founder & CEO",
     "href": "person-palantir-alex-karp.html",
     "id": "palantir-alex-karp",
     "researched": true
    },
    {
     "name": "Stephen Cohen",
     "title": "Co-Founder & President",
     "href": "person-palantir-stephen-cohen.html",
     "id": "palantir-stephen-cohen",
     "researched": true
    },
    {
     "name": "Peter Thiel",
     "title": "Co-Founder & Chairman of the Board",
     "href": "person-palantir-peter-thiel.html",
     "id": "palantir-peter-thiel",
     "researched": true
    },
    {
     "name": "Shyam Sankar",
     "title": "Chief Technology Officer",
     "href": "person-palantir-shyam-sankar.html",
     "id": "palantir-shyam-sankar",
     "researched": true
    }
   ]
  },
  {
   "slug": "perplexity",
   "name": "Perplexity",
   "website": "https://www.perplexity.ai",
   "linkedin": "https://www.linkedin.com/company/perplexity-ai",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model"
   ],
   "description": "Went from a $121M valuation in April 2023 to roughly $20B by September 2025, on annualised revenue reported above $450M by March 2026. The strategic bet is Comet — a free agentic browser — on the thesis that owning the browsing surface beats owning the underlying model.",
   "revenue": "~$450–500M ARR",
   "status": "full",
   "hasPdf": false,
   "dash": "perplexity-dashboard.html",
   "pdf": "perplexity-one-sheet.pdf",
   "people": [
    {
     "name": "Aravind Srinivas",
     "title": "Co-Founder & Chief Executive Officer",
     "href": "person-perplexity-aravind-srinivas.html",
     "id": "perplexity-aravind-srinivas",
     "researched": true
    },
    {
     "name": "Denis Yarats",
     "title": "Co-Founder & Chief Technology Officer",
     "href": "person-perplexity-denis-yarats.html",
     "id": "perplexity-denis-yarats",
     "researched": false
    }
   ]
  },
  {
   "slug": "pwc",
   "name": "PwC",
   "website": "https://www.pwc.com",
   "linkedin": "https://www.linkedin.com/company/pwc",
   "group": "SI / Consulting",
   "tags": [
    "Consulting / Advisory",
    "System Integrator"
   ],
   "description": "$56.9B of FY2025 revenue on 2.7% growth — the slowest of the Big Four — while cutting 5,600 roles and quietly dropping the previous leadership's pledge to add 100,000 people by mid-2026. Against that, it invested nearly $1.5B in AI capability and upskilled over 315,000 of its own people.",
   "revenue": "$56.9B (FY25)",
   "status": "full",
   "hasPdf": false,
   "dash": "pwc-dashboard.html",
   "pdf": "pwc-one-sheet.pdf",
   "people": [
    {
     "name": "Mohamed Kande",
     "title": "Global Chairman",
     "href": "person-pwc-mohamed-kande.html",
     "id": "pwc-mohamed-kande",
     "researched": true
    }
   ]
  },
  {
   "slug": "salesforce",
   "name": "Salesforce",
   "website": "https://www.salesforce.com",
   "linkedin": "https://www.linkedin.com/company/salesforce",
   "group": "Enterprise software",
   "tags": [
    "CRM",
    "Analytics & BI",
    "Automation / RPA"
   ],
   "description": "Agentforce ARR reached $800M in FY2026, up 169%, and passed $1.2B by Q1 FY2027 — up 205%. Combined Agentforce and Data 360 ARR exceeds $2.9B. Salesforce has started reporting Agentic Work Units, a measure of tasks completed rather than licences sold.",
   "revenue": "$41.5B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "salesforce-dashboard.html",
   "pdf": "salesforce-one-sheet.pdf",
   "people": [
    {
     "name": "Marc Benioff",
     "title": "Chair & Chief Executive Officer",
     "href": "person-salesforce-marc-benioff.html",
     "id": "salesforce-marc-benioff",
     "researched": true
    },
    {
     "name": "Robin Washington",
     "title": "President, Chief Financial and Operating Officer",
     "href": "person-salesforce-robin-washington.html",
     "id": "salesforce-robin-washington",
     "researched": true
    }
   ]
  },
  {
   "slug": "sand-technologies",
   "name": "Sand Technologies",
   "website": "https://www.sandtech.com",
   "linkedin": "https://www.linkedin.com/company/sand-technologies",
   "group": "Physical / Industrial AI",
   "tags": [
    "Physical / Industrial AI",
    "Digital Twin",
    "System Integrator"
   ],
   "description": "Private Physical AI vendor with deep emerging-market delivery reach via its ALX talent pipeline; deployed in 18+ countries with a services-heavy, project-based model rather than disclosed SaaS metrics.",
   "revenue": "$15–67M (est.)",
   "status": "full",
   "hasPdf": true,
   "dash": "sand-technologies-dashboard.html",
   "pdf": "Sand-Technologies-One-Sheet.pdf",
   "people": [
    {
     "name": "Fred Swaniker",
     "title": "Founder & CEO",
     "href": "person-sand-technologies-fred-swaniker.html",
     "id": "sand-technologies-fred-swaniker",
     "researched": true
    },
    {
     "name": "Danai Mavunga",
     "title": "Chief Operating Officer",
     "href": "person-sand-technologies-danai-mavunga.html",
     "id": "sand-technologies-danai-mavunga",
     "researched": true
    },
    {
     "name": "David Bratt",
     "title": "Chief Financial Officer",
     "href": "person-sand-technologies-david-bratt.html",
     "id": "sand-technologies-david-bratt",
     "researched": true
    },
    {
     "name": "George Ionita",
     "title": "Chief Technology Officer",
     "href": "person-sand-technologies-george-ionita.html",
     "id": "sand-technologies-george-ionita",
     "researched": false
    }
   ]
  },
  {
   "slug": "sap",
   "name": "SAP",
   "website": "https://www.sap.com",
   "linkedin": "https://www.linkedin.com/company/sap",
   "group": "Enterprise software",
   "tags": [
    "ERP",
    "Analytics & BI"
   ],
   "description": "The dominant ERP vendor, with a record €77B total cloud backlog and Business AI included in two-thirds of Q4 2025 cloud order entry. Joule customer numbers grew ninefold across 2025, and SAP is now shifting its product roadmap from features toward autonomous agents.",
   "revenue": "€9.7B/qtr (Q4 25)",
   "status": "full",
   "hasPdf": false,
   "dash": "sap-dashboard.html",
   "pdf": "sap-one-sheet.pdf",
   "people": [
    {
     "name": "Christian Klein",
     "title": "Chief Executive Officer",
     "href": "person-sap-christian-klein.html",
     "id": "sap-christian-klein",
     "researched": true
    },
    {
     "name": "Dominik Asam",
     "title": "Chief Financial Officer",
     "href": "person-sap-dominik-asam.html",
     "id": "sap-dominik-asam",
     "researched": true
    }
   ]
  },
  {
   "slug": "servicenow",
   "name": "ServiceNow",
   "website": "https://www.servicenow.com",
   "linkedin": "https://www.linkedin.com/company/servicenow",
   "group": "Enterprise software",
   "tags": [
    "ITSM / Workflow",
    "Automation / RPA"
   ],
   "description": "Growing subscription revenue at 24.5% at a scale approaching $16B, with AI annual contract value passing $1B and accelerating more than 40% quarter over quarter. Agentic deployments of ServiceNow AI increased ninefold in nine months, and more than 100 billion workflows run on the platform each year.",
   "revenue": "$15.8B (FY26 guide)",
   "status": "full",
   "hasPdf": false,
   "dash": "servicenow-dashboard.html",
   "pdf": "servicenow-one-sheet.pdf",
   "people": [
    {
     "name": "Bill McDermott",
     "title": "Chairman & Chief Executive Officer",
     "href": "person-servicenow-bill-mcdermott.html",
     "id": "servicenow-bill-mcdermott",
     "researched": true
    },
    {
     "name": "Gina Mastantuono",
     "title": "President & Chief Financial Officer",
     "href": "person-servicenow-gina-mastantuono.html",
     "id": "servicenow-gina-mastantuono",
     "researched": true
    },
    {
     "name": "Amit Zavery",
     "title": "President, Chief Product Officer & Chief Operating Officer",
     "href": "person-servicenow-amit-zavery.html",
     "id": "servicenow-amit-zavery",
     "researched": true
    },
    {
     "name": "Pat Casey",
     "title": "Chief Technology Officer & EVP of DevOps",
     "href": "person-servicenow-pat-casey.html",
     "id": "servicenow-pat-casey",
     "researched": false
    }
   ]
  },
  {
   "slug": "siemens-xcelerator",
   "name": "Siemens Xcelerator",
   "website": "https://www.siemens.com/global/en/company/topic-areas/siemens-xcelerator.html",
   "linkedin": "https://www.linkedin.com/company/siemens",
   "group": "Physical / Industrial AI",
   "tags": [
    "Physical / Industrial AI",
    "Digital Twin",
    "Engineering Software"
   ],
   "description": "The broadest ecosystem on this list by design — an open marketplace of Siemens and third-party tools rather than a single unified product, backed by one of the largest industrial conglomerates in the world.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": true,
   "dash": "siemens-xcelerator-dashboard.html",
   "pdf": "siemens-xcelerator-one-sheet.pdf",
   "people": [
    {
     "name": "Roland Busch",
     "title": "President & CEO, Siemens AG",
     "href": "person-siemens-xcelerator-roland-busch.html",
     "id": "siemens-xcelerator-roland-busch",
     "researched": true
    },
    {
     "name": "Cedrik Neike",
     "title": "Managing Board Member & CEO, Digital Industries",
     "href": "person-siemens-xcelerator-cedrik-neike.html",
     "id": "siemens-xcelerator-cedrik-neike",
     "researched": true
    }
   ]
  },
  {
   "slug": "snowflake",
   "name": "Snowflake",
   "website": "https://www.snowflake.com",
   "linkedin": "https://www.linkedin.com/company/snowflake-computing",
   "group": "Data platform",
   "tags": [
    "Data Platform",
    "Analytics & BI"
   ],
   "description": "Product revenue accelerated from 26% growth in Q1 FY2026 to 34% by Q1 FY2027, with RPO up 42% to $9.77B and net revenue retention at 125%. Snowflake Intelligence reached over 2,500 accounts within three months of launch — the fastest adoption ramp in the company's history.",
   "revenue": "$1.23B/qtr (Q4 FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "snowflake-dashboard.html",
   "pdf": "snowflake-one-sheet.pdf",
   "people": [
    {
     "name": "Sridhar Ramaswamy",
     "title": "Chief Executive Officer",
     "href": "person-snowflake-sridhar-ramaswamy.html",
     "id": "snowflake-sridhar-ramaswamy",
     "researched": false
    }
   ]
  },
  {
   "slug": "syntax",
   "name": "Syntax",
   "website": "https://www.syntax.com",
   "linkedin": "https://www.linkedin.com/company/syntax",
   "group": "SI / Consulting",
   "tags": [
    "Managed Services",
    "ERP"
   ],
   "description": "A 50-year-old specialist that does one thing: run mission-critical SAP and Oracle environments for over 1,000 customers, concentrated in manufacturing, automotive, energy and mining. It holds SAP Gold Partner status, Oracle, AWS Advanced, Microsoft Gold and IBM Silver partnerships.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": false,
   "dash": "syntax-dashboard.html",
   "pdf": "syntax-one-sheet.pdf",
   "people": [
    {
     "name": "Christian Primeau",
     "title": "Global Chief Executive Officer",
     "href": "person-syntax-christian-primeau.html",
     "id": "syntax-christian-primeau",
     "researched": false
    }
   ]
  },
  {
   "slug": "tcs",
   "name": "Tata Consultancy Services",
   "website": "https://www.tcs.com",
   "linkedin": "https://www.linkedin.com/company/tata-consultancy-services",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "The largest Indian IT services firm and, on the evidence here, the one converting AI into revenue fastest: annualised AI revenue passed $1.8B in Q3 FY2026, $2.3B in Q4 and $2.6B by Q1 FY2027, against a stated ambition to become the world's largest AI-led technology services company.",
   "revenue": "$30B+ (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "tcs-dashboard.html",
   "pdf": "tcs-one-sheet.pdf",
   "people": [
    {
     "name": "K Krithivasan",
     "title": "Chief Executive Officer & Managing Director",
     "href": "person-tcs-k-krithivasan.html",
     "id": "tcs-k-krithivasan",
     "researched": false
    },
    {
     "name": "Aarthi Subramanian",
     "title": "Executive Director, President & Chief Operating Officer",
     "href": "person-tcs-aarthi-subramanian.html",
     "id": "tcs-aarthi-subramanian",
     "researched": false
    }
   ]
  },
  {
   "slug": "tribola-tech",
   "name": "Tribola Tech",
   "website": "https://www.tribolatech.com",
   "linkedin": "https://www.linkedin.com/company/tribolatech-inc",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "CRM",
    "Data Platform"
   ],
   "description": "The smallest vendor tracked in this app by a wide margin, and the least documented. It positions around complex customer and operational workflows that do not fit inside a single platform, with a stated approach of defining the business problem before selecting technology.",
   "revenue": "Not disclosed",
   "status": "full",
   "hasPdf": false,
   "dash": "tribola-tech-dashboard.html",
   "pdf": "tribola-tech-one-sheet.pdf",
   "people": []
  },
  {
   "slug": "uipath",
   "name": "UiPath",
   "website": "https://www.uipath.com",
   "linkedin": "https://www.linkedin.com/company/uipath",
   "group": "Automation",
   "tags": [
    "Automation / RPA"
   ],
   "description": "$1.853B of ARR growing 11%, with the argument that enterprises scaling AI need something that executes reliably rather than something that reasons well. Dines frames UiPath as the execution layer enterprises trust for mission-critical processes in the agentic era.",
   "revenue": "$1.85B ARR (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "uipath-dashboard.html",
   "pdf": "uipath-one-sheet.pdf",
   "people": [
    {
     "name": "Daniel Dines",
     "title": "Founder, Chief Executive Officer & Executive Chairman",
     "href": "person-uipath-daniel-dines.html",
     "id": "uipath-daniel-dines",
     "researched": false
    },
    {
     "name": "Raghu Malpani",
     "title": "Chief Product & Technology Officer",
     "href": "person-uipath-raghu-malpani.html",
     "id": "uipath-raghu-malpani",
     "researched": false
    }
   ]
  },
  {
   "slug": "wipro",
   "name": "Wipro",
   "website": "https://www.wipro.com",
   "linkedin": "https://www.linkedin.com/company/wipro",
   "group": "SI / Consulting",
   "tags": [
    "System Integrator",
    "Managed Services"
   ],
   "description": "The slowest-growing of the India-heritage integrators tracked here, with Q1 FY2027 IT services revenue up just 0.9% at constant currency and declining sequentially. Its response is a structural one — a new AI Native Business and Platforms unit pivoting to a services-as-a-software model.",
   "revenue": "~$10B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "wipro-dashboard.html",
   "pdf": "wipro-one-sheet.pdf",
   "people": [
    {
     "name": "Srinivas Pallia",
     "title": "Chief Executive Officer & Managing Director",
     "href": "person-wipro-srinivas-pallia.html",
     "id": "wipro-srinivas-pallia",
     "researched": false
    },
    {
     "name": "Aparna C. Iyer",
     "title": "Chief Financial Officer",
     "href": "person-wipro-aparna-c-iyer.html",
     "id": "wipro-aparna-c-iyer",
     "researched": false
    },
    {
     "name": "Rishad A. Premji",
     "title": "Executive Chairman",
     "href": "person-wipro-rishad-a-premji.html",
     "id": "wipro-rishad-a-premji",
     "researched": false
    }
   ]
  },
  {
   "slug": "workday",
   "name": "Workday",
   "website": "https://www.workday.com",
   "linkedin": "https://www.linkedin.com/company/workday",
   "group": "Enterprise software",
   "tags": [
    "ERP"
   ],
   "description": "Subscription revenue grew from $7.7B to $8.8B in FY2026, with subscription backlog of $25.96B, up 17%. More than 75% of core customers use Workday Illuminate, and over a billion AI actions ran on the platform during the year.",
   "revenue": "$9.6B (FY26)",
   "status": "full",
   "hasPdf": false,
   "dash": "workday-dashboard.html",
   "pdf": "workday-one-sheet.pdf",
   "people": [
    {
     "name": "Carl Eschenbach",
     "title": "Chief Executive Officer",
     "href": "person-workday-carl-eschenbach.html",
     "id": "workday-carl-eschenbach",
     "researched": false
    },
    {
     "name": "Zane Rowe",
     "title": "Chief Financial Officer",
     "href": "person-workday-zane-rowe.html",
     "id": "workday-zane-rowe",
     "researched": false
    }
   ]
  },
  {
   "slug": "xai",
   "name": "xAI",
   "website": "https://x.ai",
   "linkedin": "https://www.linkedin.com/company/xai",
   "group": "Frontier AI / LLM",
   "tags": [
    "LLM / Foundation Model"
   ],
   "description": "Raised $20B in January 2026 at a $230B valuation, then merged into SpaceX a month later at roughly $250B. Colossus grew from 100,000 GPUs at its October 2024 launch to 555,000, with the two Memphis clusters together housing over a million GPUs and drawing 2 gigawatts.",
   "revenue": "~$500M ARR",
   "status": "full",
   "hasPdf": false,
   "dash": "xai-dashboard.html",
   "pdf": "xai-one-sheet.pdf",
   "people": [
    {
     "name": "Elon Musk",
     "title": "Founder",
     "href": "person-xai-elon-musk.html",
     "id": "xai-elon-musk",
     "researched": false
    }
   ]
  }
 ]
};
