# -*- coding: utf-8 -*-
"""
build_site.py — generates every page of the GIP vendor tracker app.

Run from anywhere:  python3 scripts/build_site.py
Writes into the repo root (flat folder — all links are relative).
"""
import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

from research_data import VENDORS, TAXONOMY, dash_href, pdf_href, person_href, person_id
import people_research

CSS = open(os.path.join(SCRIPT_DIR, "shared.css")).read() + \
      open(os.path.join(SCRIPT_DIR, "app.css")).read()

BUILD_DATE = "September 15, 2026"

NAV = [
    ("index.html", "Overview"),
    ("tracker.html", "Engagement tracker"),
    ("scorecard.html", "Scorecard"),
    ("people.html", "Contacts"),
]


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def nav(current):
    out = []
    for href, label in NAV:
        cls = ' class="current"' if href == current else ""
        out.append(f'<a href="{href}"{cls}>{label}</a>')
    return f'<div class="appnav">{"".join(out)}</div>'


def shell(title, kicker, h1, tagline, body, current, kpis="", scripts="", back=None):
    top = nav(current) if current else (
        f'<div class="topnav"><a class="back-link" href="{back[0]}">&larr; {back[1]}</a></div>'
        if back else "")
    kpi_html = f'<div class="kpi-row">{kpis}</div>' if kpis else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<style>
{CSS}
</style>
</head>
<body>

<header class="hero">
  <div class="hero-inner">
    {top}
    <div class="kicker"><span class="dot"></span>{kicker}</div>
    <h1>{h1}</h1>
    <p class="tagline">{tagline}</p>
    {kpi_html}
  </div>
</header>

<div class="wrap">
{body}
</div>

<script src="xlsx.full.min.js"></script>
<script src="gip-loader.js"></script>
{scripts}
</body>
</html>
"""


def kpi(num, lbl):
    return f'<div class="kpi"><div class="num">{num}</div><div class="lbl">{lbl}</div></div>'


# =====================================================================
#  app-data.js — the research layer, exposed to the browser
# =====================================================================
def write_app_data():
    payload = {
        "buildDate": BUILD_DATE,
        "taxonomy": TAXONOMY,
        "vendors": [{
            "slug": v["slug"], "name": v["name"], "website": v["website"],
            "linkedin": v["linkedin"], "group": v["group"], "tags": v["tags"],
            "description": v["description"], "revenue": v["revenue_short"],
            "status": v["research_status"], "hasPdf": v["has_pdf"],
            "dash": dash_href(v["slug"]), "pdf": pdf_href(v["slug"]),
            "people": [{"name": p["name"], "title": re.sub("&amp;", "&", p["title"]),
                        "href": person_href(v["slug"], p["name"]),
                        "id": person_id(v["slug"], p["name"]),
                        "researched": people_research.get(person_id(v["slug"], p["name"])) is not None}
                       for p in v["people"]],
        } for v in VENDORS],
    }
    js = "/* generated by build_site.py — do not edit by hand */\n" \
         "window.APP = " + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n"
    open(os.path.join(ROOT, "app-data.js"), "w").write(js)


# =====================================================================
#  Overview
# =====================================================================
def build_overview():
    full = sum(1 for v in VENDORS if v["research_status"] == "full")
    body = f"""
  <div id="gip-loadbar" class="loadbar">Reading gip-tracker.xlsx…</div>

  <section>
    <div class="sec-head"><span class="sec-num">01</span><h2>All tracked vendors</h2></div>
    <div class="sec-note">Filter by what a vendor actually does. Selecting more than one category shows
    vendors matching <b>any</b> of them. Engagement counts and scores come from your tracker workbook.</div>

    <div class="filterbar">
      <h4>What the vendor does</h4>
      <div class="fchips" id="chips"></div>
      <div class="filter-meta">
        <input class="searchbox" id="q" type="search" placeholder="Search vendor name or description…">
        <label style="display:flex; gap:6px; align-items:center; cursor:pointer;">
          <input type="checkbox" id="engaged"> Only vendors we're engaged with
        </label>
        <button class="linkbtn" id="clear">Clear filters</button>
        <span id="count"></span>
      </div>
    </div>

    <div class="vendor-grid" id="grid"></div>
    <div id="none" class="empty" style="display:none;"><b>Nothing matches</b>Try clearing a filter.</div>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">02</span><h2>Vendor index</h2></div>
    <div class="sec-note">Every vendor, alphabetically, with its categories and current engagement status.</div>
    <div class="tscroll">
      <table class="dtable">
        <thead><tr>
          <th style="width:18%;">Vendor</th><th style="width:30%;">Categories</th>
          <th style="width:12%;">Research</th><th style="width:12%;">Threads</th>
          <th style="width:14%;">PortCos</th><th style="width:14%;">Score</th>
        </tr></thead>
        <tbody id="indexrows"></tbody>
      </table>
    </div>
  </section>

  <footer>
    <b>Two data layers.</b> Market research (who the vendor is, what they sell, public sources) is generated
    into <code>app-data.js</code> and can be regenerated at any time without touching your data. GIP engagement
    data lives only in <code>gip-tracker.xlsx</code> on your machine and is read in the browser.
    <b>{full} of {len(VENDORS)}</b> vendors have completed deep research; the rest show a profile shell until
    their research pass runs. Built {BUILD_DATE}.
  </footer>
"""
    scripts = """<script src="app-data.js"></script>
<script>
(function(){
  var active = {}, q = "", engagedOnly = false, DATA = null;

  function counts(){
    var c = {};
    APP.vendors.forEach(function(v){ v.tags.forEach(function(t){ c[t]=(c[t]||0)+1; }); });
    return c;
  }
  function drawChips(){
    var c = counts();
    document.getElementById("chips").innerHTML = APP.taxonomy.map(function(t){
      return '<span class="fchip'+(active[t]?' on':'')+'" data-t="'+GIP.esc(t)+'">'+
             GIP.esc(t)+'<span class="n">'+(c[t]||0)+'</span></span>';
    }).join("");
    Array.prototype.forEach.call(document.querySelectorAll(".fchip"), function(el){
      el.onclick = function(){
        var t = el.getAttribute("data-t");
        if(active[t]) delete active[t]; else active[t]=1;
        drawChips(); draw();
      };
    });
  }
  function eng(v){
    if(!DATA) return {n:0,p:0,score:null};
    var rows = DATA.byVendor[v.name.toLowerCase()] || [];
    var pcs = {}; rows.forEach(function(r){ if(r.portco) pcs[r.portco]=1; });
    return {n:rows.length, p:Object.keys(pcs).length, score:DATA.scores[v.name.toLowerCase()]||null};
  }
  function match(v){
    var tags = Object.keys(active);
    if(tags.length && !tags.some(function(t){ return v.tags.indexOf(t)>=0; })) return false;
    if(q && (v.name+" "+v.description).toLowerCase().indexOf(q)<0) return false;
    if(engagedOnly && eng(v).n===0) return false;
    return true;
  }
  function card(v){
    var e = eng(v);
    var badge = v.status==="full"
      ? '<span class="badge full">Researched</span>'
      : '<span class="badge pending">Research pending</span>';
    var scoreBadge = e.score ? '<span class="badge score">Score '+e.score.total+'</span>' : '';
    var engLine = e.n
      ? '<div class="vcard-kpi"><div class="k-num">'+e.n+' thread'+(e.n===1?'':'s')+
        ' &middot; '+e.p+' PortCo'+(e.p===1?'':'s')+'</div><div class="k-lbl">Live GIP engagement</div></div>'
      : '<div class="vcard-kpi"><div class="k-num" style="color:var(--ink-3);">No engagement logged</div>'+
        '<div class="k-lbl">Add a row in the tracker workbook</div></div>';
    return '<div class="vcard">'+
      '<div class="vcard-top"><a class="vcard-name" href="'+v.website+'" target="_blank" rel="noopener">'+
        GIP.esc(v.name)+' &#8599;</a>'+badge+'</div>'+
      '<div class="vcard-desc">'+GIP.esc(v.description)+'</div>'+
      '<div class="vcard-tags">'+v.tags.map(function(t){return '<span class="tag">'+GIP.esc(t)+'</span>';}).join("")+'</div>'+
      engLine+
      '<div class="vcard-actions"><a class="btn secondary" href="'+v.dash+'">White page</a>'+
      (v.hasPdf?'<a class="btn secondary" href="'+v.pdf+'" download>PDF &darr;</a>':'')+
      scoreBadge+'</div></div>';
  }
  function draw(){
    var list = APP.vendors.filter(match);
    document.getElementById("grid").innerHTML = list.map(card).join("");
    document.getElementById("none").style.display = list.length ? "none" : "block";
    document.getElementById("count").innerHTML = "<b>"+list.length+"</b> of "+APP.vendors.length+" vendors";
    document.getElementById("indexrows").innerHTML = list.map(function(v){
      var e = eng(v);
      return '<tr><td class="vname"><a href="'+v.dash+'">'+GIP.esc(v.name)+'</a></td>'+
        '<td>'+v.tags.join(" &middot; ")+'</td>'+
        '<td>'+(v.status==="full"?'<span class="pill s-live">Complete</span>':'<span class="pill s-early">Pending</span>')+'</td>'+
        '<td>'+(e.n||"—")+'</td><td>'+(e.p||"—")+'</td>'+
        '<td>'+(e.score?'<b>'+e.score.total+'</b> / 100':"—")+'</td></tr>';
    }).join("");
  }
  document.getElementById("q").oninput = function(){ q=this.value.toLowerCase(); draw(); };
  document.getElementById("engaged").onchange = function(){ engagedOnly=this.checked; draw(); };
  document.getElementById("clear").onclick = function(){
    active={}; q=""; engagedOnly=false;
    document.getElementById("q").value=""; document.getElementById("engaged").checked=false;
    drawChips(); draw();
  };
  drawChips(); draw();
  GIP.ready(function(d){ DATA=d; draw(); });
})();
</script>"""
    html = shell(
        "GIP Vendor & Technology Tracker",
        f"GIP AI PROGRAM &nbsp;·&nbsp; VENDOR TRACKER &nbsp;·&nbsp; {BUILD_DATE.upper()}",
        "Vendor &amp; Technology Tracker",
        f"{len(VENDORS)} vendors across frontier AI, enterprise software, data platforms, industrial AI and "
        "systems integration &mdash; what they do, who we know there, and where every GIP engagement stands.",
        body, "index.html",
        kpis=kpi(len(VENDORS), "Vendors tracked") +
             kpi(len(TAXONOMY), "Categories") +
             kpi(full, "Deep-research white pages") +
             '<div class="kpi"><div class="num" id="k-threads">—</div><div class="lbl">Engagement threads logged</div></div>' +
             '<div class="kpi"><div class="num" id="k-portcos">—</div><div class="lbl">PortCos introduced</div></div>',
        scripts=scripts + """
<script>
GIP.ready(function(d){
  document.getElementById("k-threads").textContent = d.engagements.length || "0";
  var p={}; d.engagements.forEach(function(e){ if(e.portco) p[e.portco]=1; });
  document.getElementById("k-portcos").textContent = Object.keys(p).length || "0";
});
</script>""")
    open(os.path.join(ROOT, "index.html"), "w").write(html)
    open(os.path.join(ROOT, "market-overview.html"), "w").write(html)


# =====================================================================
#  Tracker
# =====================================================================
def build_tracker():
    body = """
  <div id="gip-loadbar" class="loadbar">Reading gip-tracker.xlsx…</div>

  <section>
    <div class="sec-head"><span class="sec-num">01</span><h2>Engagement threads</h2></div>
    <div class="sec-note">Every row is one vendor / PortCo / use-case thread from the
    <b>Engagements</b> sheet. A vendor appears as many times as it has threads. Edit the workbook
    and reload this page to update.</div>

    <div class="filterbar">
      <h4>Filter</h4>
      <div class="fchips" id="statuschips"></div>
      <div class="filter-meta">
        <input class="searchbox" id="q" type="search" placeholder="Search vendor, PortCo, person, use case…">
        <select class="searchbox" id="vendorsel" style="flex:0 0 200px;"><option value="">All vendors</option></select>
        <button class="linkbtn" id="clear">Clear filters</button>
        <span id="count"></span>
      </div>
    </div>

    <div class="tscroll">
      <table class="dtable">
        <thead><tr>
          <th style="width:12%;">Vendor</th><th style="width:11%;">Requested by</th>
          <th style="width:16%;">Connection &amp; reason</th><th style="width:11%;">PortCo</th>
          <th style="width:19%;">Use case</th><th style="width:10%;">Status</th>
          <th style="width:10%;">Owner</th><th style="width:11%;">Next step</th>
        </tr></thead>
        <tbody id="rows"></tbody>
      </table>
    </div>
    <div id="none" class="empty" style="display:none;"><b>No engagement rows yet</b>
      Add rows to the Engagements sheet of gip-tracker.xlsx, then reload.</div>
  </section>

  <footer>
    This page reads your workbook directly and never writes to it. To change anything, edit
    <code>gip-tracker.xlsx</code> and reload. Status values come from the <b>Lists</b> sheet.
  </footer>
"""
    scripts = """<script src="app-data.js"></script>
<script>
(function(){
  var DATA=null, active={}, q="", vendor="";
  var STATUSES=["Requested","Intro Made","Discovery","Pilot Scoping","Pilot Active",
                "Deployed / In Production","Paused","No Fit","Dormant"];

  function drawChips(){
    document.getElementById("statuschips").innerHTML = STATUSES.map(function(s){
      var n = DATA ? DATA.engagements.filter(function(e){return e.status===s;}).length : 0;
      return '<span class="fchip'+(active[s]?' on':'')+'" data-s="'+GIP.esc(s)+'">'+
             GIP.esc(s)+'<span class="n">'+n+'</span></span>';
    }).join("");
    Array.prototype.forEach.call(document.querySelectorAll("#statuschips .fchip"), function(el){
      el.onclick=function(){
        var s=el.getAttribute("data-s");
        if(active[s]) delete active[s]; else active[s]=1;
        drawChips(); draw();
      };
    });
  }
  function drawVendorSel(){
    if(!DATA) return;
    var names={}; DATA.engagements.forEach(function(e){ names[e.vendor]=1; });
    var sel=document.getElementById("vendorsel");
    sel.innerHTML='<option value="">All vendors</option>'+Object.keys(names).sort().map(function(n){
      return '<option value="'+GIP.esc(n)+'">'+GIP.esc(n)+'</option>';
    }).join("");
    sel.value=vendor;
  }
  function match(e){
    var st=Object.keys(active);
    if(st.length && st.indexOf(e.status)<0) return false;
    if(vendor && e.vendor!==vendor) return false;
    if(q){
      var hay=[e.vendor,e.requestedBy,e.connection,e.reason,e.portco,e.useCase,e.useArea,
               e.owner,e.nextStep,e.notes].join(" ").toLowerCase();
      if(hay.indexOf(q)<0) return false;
    }
    return true;
  }
  function slugFor(name){
    var v=APP.vendors.filter(function(x){return x.name.toLowerCase()===name.toLowerCase();})[0];
    return v?v.dash:null;
  }
  function row(e){
    var dash=slugFor(e.vendor);
    return '<tr>'+
      '<td class="vname">'+(dash?'<a href="'+dash+'">'+GIP.esc(e.vendor)+'</a>':GIP.esc(e.vendor))+'</td>'+
      '<td>'+GIP.esc(e.requestedBy||"—")+(e.requesterOrg?'<br><span style="color:var(--ink-3);font-size:11.5px;">'+GIP.esc(e.requesterOrg)+'</span>':'')+'</td>'+
      '<td>'+GIP.esc(e.connection||"—")+(e.reason?'<br><span style="color:var(--ink-3);">'+GIP.esc(e.reason)+'</span>':'')+'</td>'+
      '<td>'+GIP.esc(e.portco||"—")+'</td>'+
      '<td>'+GIP.esc(e.useCase||"—")+(e.useArea?'<br><span class="tag">'+GIP.esc(e.useArea)+'</span>':'')+'</td>'+
      '<td><span class="pill '+GIP.statusClass(e.status)+'">'+GIP.esc(e.status||"—")+'</span>'+
        (e.lastTouch?'<br><span style="color:var(--ink-3);font-size:11.5px;">'+GIP.fmtDate(e.lastTouch)+'</span>':'')+'</td>'+
      '<td>'+GIP.esc(e.owner||"—")+'</td>'+
      '<td>'+GIP.esc(e.nextStep||"—")+(e.nextStepDue?'<br><span style="color:var(--ink-3);font-size:11.5px;">due '+GIP.fmtDate(e.nextStepDue)+'</span>':'')+'</td>'+
      '</tr>';
  }
  function draw(){
    var list = DATA ? DATA.engagements.filter(match) : [];
    document.getElementById("rows").innerHTML=list.map(row).join("");
    document.getElementById("none").style.display=list.length?"none":"block";
    document.getElementById("count").innerHTML="<b>"+list.length+"</b> thread"+(list.length===1?"":"s");
  }
  document.getElementById("q").oninput=function(){ q=this.value.toLowerCase(); draw(); };
  document.getElementById("vendorsel").onchange=function(){ vendor=this.value; draw(); };
  document.getElementById("clear").onclick=function(){
    active={}; q=""; vendor="";
    document.getElementById("q").value=""; document.getElementById("vendorsel").value="";
    drawChips(); draw();
  };
  drawChips(); draw();
  GIP.ready(function(d){ DATA=d; drawChips(); drawVendorSel(); draw(); });
})();
</script>"""
    html = shell("Engagement Tracker — GIP Vendor Tracker",
                 "GIP AI PROGRAM &nbsp;·&nbsp; ENGAGEMENT TRACKER",
                 "Engagement tracker",
                 "Who asked us to speak to them, how we're connected, which PortCos we introduced, "
                 "what they're working on, and where it stands.",
                 body, "tracker.html",
                 kpis='<div class="kpi"><div class="num" id="k1">—</div><div class="lbl">Threads</div></div>' +
                      '<div class="kpi"><div class="num" id="k2">—</div><div class="lbl">Vendors engaged</div></div>' +
                      '<div class="kpi"><div class="num" id="k3">—</div><div class="lbl">PortCos involved</div></div>' +
                      '<div class="kpi"><div class="num" id="k4">—</div><div class="lbl">Pilots or deployments</div></div>' +
                      '<div class="kpi"><div class="num" id="k5">—</div><div class="lbl">Threads with a use case</div></div>',
                 scripts=scripts + """
<script>
GIP.ready(function(d){
  var e=d.engagements, v={}, p={};
  e.forEach(function(r){ v[r.vendor]=1; if(r.portco) p[r.portco]=1; });
  document.getElementById("k1").textContent=e.length;
  document.getElementById("k2").textContent=Object.keys(v).length;
  document.getElementById("k3").textContent=Object.keys(p).length;
  document.getElementById("k4").textContent=e.filter(function(r){return /pilot|deployed/i.test(r.status);}).length;
  document.getElementById("k5").textContent=e.filter(function(r){return r.useCase.length>3;}).length;
});
</script>""")
    open(os.path.join(ROOT, "tracker.html"), "w").write(html)


# =====================================================================
#  Scorecard
# =====================================================================
def build_scorecard():
    body = """
  <div id="gip-loadbar" class="loadbar">Reading gip-tracker.xlsx…</div>

  <section>
    <div class="sec-head"><span class="sec-num">01</span><h2>How the score works</h2></div>
    <div class="callout">
      Each vendor is scored out of 100 from its engagement threads &mdash; not from how good the vendor is.
      A high score means a broad, deep, live relationship; a low score means we've barely started.
      <b>Breadth (30)</b> distinct PortCos introduced, capped at five.
      <b>Depth (30)</b> the furthest status any thread has reached.
      <b>Momentum (20)</b> how recently anything moved.
      <b>Substance (20)</b> the share of threads with a real use case written down.
      A number in <b>Score Override</b> on the Vendors sheet replaces the calculation entirely &mdash;
      use it when the arithmetic misses something you know.
    </div>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">02</span><h2>Vendor scorecards</h2></div>
    <div class="sec-note">Ranked by score. Only vendors with at least one engagement thread appear here.</div>
    <div class="score-grid" id="cards"></div>
    <div id="none" class="empty" style="display:none;"><b>Nothing to score yet</b>
      Add engagement rows to gip-tracker.xlsx and the scorecards appear here.</div>
  </section>

  <footer>
    The score measures <b>our engagement</b>, not vendor quality. A vendor can be excellent and score zero
    because we haven't done anything with them yet.
  </footer>
"""
    scripts = """<script src="app-data.js"></script>
<script>
(function(){
  function bar(p){
    return '<div class="sbar"><div class="sbar-lbl"><b>'+GIP.esc(p.label)+'</b><span>'+GIP.esc(p.note)+'</span></div>'+
      '<div class="sbar-track"><div class="sbar-fill" style="width:'+Math.round(p.pct*100)+'%;"></div></div></div>';
  }
  function slugFor(name){
    var v=APP.vendors.filter(function(x){return x.name.toLowerCase()===name.toLowerCase();})[0];
    return v?v.dash:null;
  }
  GIP.ready(function(d){
    var keys=Object.keys(d.scores).sort(function(a,b){ return d.scores[b].total-d.scores[a].total; });
    if(!keys.length){ document.getElementById("none").style.display="block"; return; }
    document.getElementById("cards").innerHTML=keys.map(function(k){
      var s=d.scores[k], rows=d.byVendor[k], name=rows[0].vendor, dash=slugFor(name);
      var v=d.vendors[k]||{};
      return '<div class="scard">'+
        '<div class="scard-top">'+
          (dash?'<a class="scard-name" href="'+dash+'">'+GIP.esc(name)+'</a>'
               :'<span class="scard-name">'+GIP.esc(name)+'</span>')+
          '<div class="scard-score">'+s.total+'<span class="of"> /100</span></div></div>'+
        '<div class="scard-sub">'+s.threads+' thread'+(s.threads===1?'':'s')+' &middot; '+
          s.portcos+' PortCo'+(s.portcos===1?'':'s')+
          (v.tier?' &middot; '+GIP.esc(v.tier):'')+'</div>'+
        (s.overridden
          ? '<div class="scard-sub override-note">Manual override'+(s.overrideReason?': '+GIP.esc(s.overrideReason):'')+'</div>'
          : s.parts.map(bar).join(""))+
        '<div class="scard-foot">Last touch '+GIP.fmtDate(s.lastTouch)+
          (v.owner?' &middot; owned by '+GIP.esc(v.owner):'')+'</div>'+
        '</div>';
    }).join("");
  });
})();
</script>"""
    html = shell("Vendor Scorecard — GIP Vendor Tracker",
                 "GIP AI PROGRAM &nbsp;·&nbsp; SCORECARD",
                 "Vendor scorecard",
                 "One number per vendor summarising how far our engagement has actually gone &mdash; "
                 "breadth, depth, momentum and substance, from the tracker workbook.",
                 body, "scorecard.html",
                 kpis='<div class="kpi"><div class="num" id="k1">—</div><div class="lbl">Vendors scored</div></div>' +
                      '<div class="kpi"><div class="num" id="k2">—</div><div class="lbl">Average score</div></div>' +
                      '<div class="kpi"><div class="num" id="k3">—</div><div class="lbl">Top score</div></div>' +
                      '<div class="kpi"><div class="num" id="k4">—</div><div class="lbl">Manual overrides</div></div>',
                 scripts=scripts + """
<script>
GIP.ready(function(d){
  var k=Object.keys(d.scores), t=k.map(function(x){return d.scores[x].total;});
  document.getElementById("k1").textContent=k.length;
  document.getElementById("k2").textContent=t.length?Math.round(t.reduce(function(a,b){return a+b;},0)/t.length):"0";
  document.getElementById("k3").textContent=t.length?Math.max.apply(null,t):"0";
  document.getElementById("k4").textContent=k.filter(function(x){return d.scores[x].overridden;}).length;
});
</script>""")
    open(os.path.join(ROOT, "scorecard.html"), "w").write(html)


# =====================================================================
#  Contacts index
# =====================================================================
def build_people_index():
    body = """
  <div id="gip-loadbar" class="loadbar">Reading gip-tracker.xlsx…</div>

  <section>
    <div class="sec-head"><span class="sec-num">01</span><h2>Contacts</h2></div>
    <div class="sec-note">Executives from the research layer, plus anyone you've added to the
    <b>People</b> sheet. Cards show public professional detail; email, phone and your own notes
    come from your workbook and never leave this machine.</div>

    <div class="filterbar">
      <h4>Filter</h4>
      <div class="fchips" id="rolechips"></div>
      <div class="filter-meta">
        <input class="searchbox" id="q" type="search" placeholder="Search name, title, company…">
        <label style="display:flex; gap:6px; align-items:center; cursor:pointer;">
          <input type="checkbox" id="mine"> Only contacts we have details for
        </label>
        <button class="linkbtn" id="clear">Clear filters</button>
        <span id="count"></span>
      </div>
    </div>

    <div id="vendorbanner"></div>
    <div class="card-grid" id="cards"></div>
    <div id="none" class="empty" style="display:none;"><b>No contacts match</b>Try clearing a filter.</div>
  </section>

  <footer>
    Add anyone to the <b>People</b> sheet of <code>gip-tracker.xlsx</code> &mdash; they appear here
    immediately. Set <b>Show on Card</b> to No to keep someone out of the vendor white pages while
    still tracking them here.
  </footer>
"""
    scripts = """<script src="app-data.js"></script>
<script>
(function(){
  var DATA=null, role="", q="", mine=false;
  var VSLUG = (new URLSearchParams(location.search)).get("vendor") || "";
  var ROLES=["CEO","CTO","President","COO","CFO","Chief AI / Data Officer","Sales / Account Lead","Other"];

  function all(){
    var out=[];
    APP.vendors.forEach(function(v){
      if(VSLUG && v.slug !== VSLUG) return;
      v.people.forEach(function(p){
        var extra = DATA && DATA.peopleById[p.id] ? DATA.peopleById[p.id] : null;
        out.push({name:p.name,title:p.title,vendor:v.name,href:p.href,id:p.id,
                  dash:v.dash,extra:extra,seeded:true,researched:p.researched});
      });
    });
    if(DATA){
      DATA.people.forEach(function(p){
        if(p.id && out.some(function(o){return o.id===p.id;})) return;
        var v=APP.vendors.filter(function(x){return x.name.toLowerCase()===p.vendor.toLowerCase();})[0];
        if(VSLUG && (!v || v.slug !== VSLUG)) return;
        out.push({name:p.name,title:p.title,vendor:p.vendor,href:null,id:p.id,
                  dash:v?v.dash:null,extra:p,seeded:false});
      });
    }
    return out.sort(function(a,b){ return a.vendor.localeCompare(b.vendor)||a.name.localeCompare(b.name); });
  }
  function initials(n){
    var parts=n.split(/\\s+/).filter(Boolean);
    return ((parts[0]||"")[0]||"")+((parts[parts.length-1]||"")[0]||"");
  }
  function roleOf(p){
    if(p.extra&&p.extra.roleType) return p.extra.roleType;
    var t=(p.title||"").toLowerCase();
    if(t.indexOf("chief technology")>=0||t.indexOf("cto")>=0) return "CTO";
    if(t.indexOf("ceo")>=0||t.indexOf("chief executive")>=0) return "CEO";
    if(t.indexOf("president")>=0) return "President";
    if(t.indexOf("operating")>=0) return "COO";
    if(t.indexOf("financial")>=0) return "CFO";
    return "Other";
  }
  function drawChips(){
    var list=all();
    document.getElementById("rolechips").innerHTML=ROLES.map(function(r){
      var n=list.filter(function(p){return roleOf(p)===r;}).length;
      return '<span class="fchip'+(role===r?' on':'')+'" data-r="'+r+'">'+r+'<span class="n">'+n+'</span></span>';
    }).join("");
    Array.prototype.forEach.call(document.querySelectorAll("#rolechips .fchip"),function(el){
      el.onclick=function(){ var r=el.getAttribute("data-r"); role=(role===r?"":r); drawChips(); draw(); };
    });
  }
  function hasDetail(p){
    var e=p.extra; return !!(e&&(e.email||e.phone||e.notes||e.howWeKnow||e.linkedin));
  }
  function card(p){
    var e=p.extra||{}, alt = roleOf(p)==="CTO";
    var rb = p.researched ? '<span class="badge full" style="margin-left:6px;">Researched</span>'
                          : (p.href ? '<span class="badge pending" style="margin-left:6px;">Pending</span>' : '');
    var foot=[];
    if(e.linkedin) foot.push('<a href="'+GIP.esc(e.linkedin)+'" target="_blank" rel="noopener">LinkedIn &#8599;</a>');
    if(e.email) foot.push('<a href="mailto:'+GIP.esc(e.email)+'">'+GIP.esc(e.email)+'</a>');
    if(e.phone) foot.push('<span>'+GIP.esc(e.phone)+'</span>');
    if(p.href) foot.push('<a href="'+p.href+'">Dashboard &rarr;</a>');
    if(p.id) foot.push('<a href="contact-'+p.id+'-one-sheet.pdf" download>White paper &darr;</a>');
    if(!foot.length) foot.push('<span class="muted">No contact details on file</span>');
    var body=[];
    if(e.background) body.push(GIP.esc(e.background));
    if(e.howWeKnow) body.push("<b>How we know them:</b> "+GIP.esc(e.howWeKnow));
    if(e.notes) body.push(GIP.esc(e.notes));
    if(!body.length) body.push('<span style="color:var(--ink-3);">Background not yet researched. '+
      'Add notes on the People sheet to fill this in.</span>');
    return '<div class="pcard">'+
      '<div class="pcard-head"><div class="mono'+(alt?' alt':'')+'">'+GIP.esc(initials(p.name))+'</div>'+
        '<div><div class="pcard-co">'+GIP.esc(p.vendor)+'</div>'+
        '<div class="pcard-name">'+GIP.esc(p.name)+rb+'</div>'+
        '<div class="pcard-role">'+GIP.esc(p.title)+'</div></div></div>'+
      '<div class="pcard-body">'+body.join("<br>")+'</div>'+
      '<div class="pcard-foot">'+foot.join("")+'</div></div>';
  }
  function draw(){
    var list=all().filter(function(p){
      if(role && roleOf(p)!==role) return false;
      if(mine && !hasDetail(p)) return false;
      if(q && (p.name+" "+p.title+" "+p.vendor).toLowerCase().indexOf(q)<0) return false;
      return true;
    });
    document.getElementById("cards").innerHTML=list.map(card).join("");
    document.getElementById("none").style.display=list.length?"none":"block";
    document.getElementById("count").innerHTML="<b>"+list.length+"</b> contact"+(list.length===1?"":"s");
  }
  document.getElementById("q").oninput=function(){ q=this.value.toLowerCase(); draw(); };
  document.getElementById("mine").onchange=function(){ mine=this.checked; draw(); };
  document.getElementById("clear").onclick=function(){
    role=""; q=""; mine=false;
    document.getElementById("q").value=""; document.getElementById("mine").checked=false;
    drawChips(); draw();
  };
  if(VSLUG){
    var vv = APP.vendors.filter(function(x){return x.slug===VSLUG;})[0];
    if(vv) document.getElementById("vendorbanner").innerHTML =
      '<div class="loadbar ok" style="margin-bottom:16px;"><div class="grow">Showing contacts at <b>'+
      GIP.esc(vv.name)+'</b> only.</div><a class="btn secondary" href="people.html">Show every vendor</a></div>';
  }
  drawChips(); draw();
  GIP.ready(function(d){ DATA=d; drawChips(); draw(); });
})();
</script>"""
    seeded = sum(len(v["people"]) for v in VENDORS)
    html = shell("Contacts — GIP Vendor Tracker",
                 "GIP AI PROGRAM &nbsp;·&nbsp; CONTACTS",
                 "Contacts",
                 "Key people at every tracked vendor &mdash; seeded with researched executives, "
                 "extended with whoever you add to the workbook.",
                 body, "people.html",
                 kpis=kpi(seeded, "Researched executives") +
                      '<div class="kpi"><div class="num" id="k1">—</div><div class="lbl">Contacts in your workbook</div></div>' +
                      '<div class="kpi"><div class="num" id="k2">—</div><div class="lbl">With email or phone</div></div>' +
                      '<div class="kpi"><div class="num" id="k3">—</div><div class="lbl">With a relationship owner</div></div>',
                 scripts=scripts + """
<script>
GIP.ready(function(d){
  document.getElementById("k1").textContent=d.people.length;
  document.getElementById("k2").textContent=d.people.filter(function(p){return p.email||p.phone;}).length;
  document.getElementById("k3").textContent=d.people.filter(function(p){return p.owner;}).length;
});
</script>""")
    open(os.path.join(ROOT, "people.html"), "w").write(html)


# =====================================================================
#  Person detail pages
# =====================================================================
def _plist(items):
    return "".join(f"<li>{esc(i)}</li>" for i in items)


def build_person_pages():
    n = 0
    for v in VENDORS:
        for p in v["people"]:
            pid = person_id(v["slug"], p["name"])
            title = re.sub("&amp;", "&", p["title"])
            ini = "".join(w[0] for w in p["name"].split() if w)[:2].upper()
            r = people_research.get(pid)

            if r:
                since = f'<p style="margin:0 0 6px; font-size:13px;"><b>In role:</b> {r["in_role_since"]}</p>' if r.get("in_role_since") else ""
                career = "".join(
                    f'<tr><td class="mname" style="white-space:nowrap;">{c.get("period", "")}</td>'
                    f'<td><b>{c["role"]}</b><br><span style="color:var(--ink-3);">{c["org"]}</span></td></tr>'
                    for c in r["career"])
                edu = ("<div class=\"side-block\"><h4>Education</h4><div class=\"chip-row\">"
                       + "".join(f'<span class="chip">{esc(e)}</span>' for e in r["education"])
                       + "</div></div>") if r.get("education") else ""
                roles = ("<div class=\"side-block\"><h4>Public roles</h4><ul style=\"margin:0; padding-left:18px; font-size:12.5px; color:var(--ink-2);\">"
                         + _plist(r["public_roles"]) + "</ul></div>") if r.get("public_roles") else ""
                notable = "".join(
                    f'<div class="qual-note" style="margin-bottom:10px;">{nb["point"]}'
                    + (f' <a href="{nb["source"]}" target="_blank" rel="noopener" style="color:var(--steel);">Source &#8599;</a>' if nb.get("source") else "")
                    + "</div>" for nb in r.get("notable", []))
                talking = ("<ul style=\"margin:0; padding-left:18px; font-size:13px; color:var(--ink-2);\">"
                           + _plist(r["talking_points"]) + "</ul>") if r.get("talking_points") else ""
                links = " &nbsp;\u00b7&nbsp; ".join(
                    f'<a href="{l["url"]}" target="_blank" rel="noopener" style="color:var(--steel);">{esc(l["label"])} &#8599;</a>'
                    for l in r.get("links", []))
                note = (f'<div class="callout" style="margin-top:14px;"><b>Research note:</b> {esc(r["notes"])}</div>'
                        if r.get("notes") else "")
                badge = '<span class="badge full">Researched</span>'
                bio_block = f"""
        <p style="font-size:14px; color:var(--ink-2); margin:0 0 14px;"><b>Today:</b> {r["focus"]}</p>
        <p style="font-size:14px; color:var(--ink-2); margin:0 0 6px;">{r["background"]}</p>
        {note}
      </div>
      <div>
        <div class="side-block">
          <h4>Role</h4>
          {since}
          <p style="margin:0 0 6px; font-size:13px;"><b>Company:</b> <a href="{dash_href(v['slug'])}" style="color:var(--steel);">{esc(v['name'])}</a></p>
        </div>
        {edu}
        {roles}
        <div class="side-block">
          <h4>Sources</h4>
          <p style="margin:0; font-size:12.5px;">{links or "&mdash;"}</p>
        </div>
        <div class="private-block" id="private">
          <h4>Your notes</h4>
          <p style="font-size:12.5px; color:var(--ink-3); margin:0;">
            Nothing on file. Fill in this person's row on the <b>People</b> sheet &mdash;
            LinkedIn, email, phone, how you know them &mdash; and it appears here.</p>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">02</span><h2>Career</h2></div>
    <table class="dtable"><tbody>{career}</tbody></table>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">03</span><h2>Worth knowing</h2></div>
    {notable or '<div class="qual-note">Nothing recorded.</div>'}
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">04</span><h2>Talking points</h2></div>
    <div class="sec-note">Derived from the research, not quoted from the person.</div>
    {talking or '<div class="qual-note">Nothing recorded.</div>'}
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">05</span><h2>Your notes</h2></div>
    <div id="ownnotes"><div class="qual-note">Nothing on file. Anything you add on the People
    sheet of gip-tracker.xlsx appears here.</div></div>
  </section>
"""
            else:
                badge = '<span class="badge pending">Research pending</span>'
                bio_block = f"""
        <div id="bio" class="qual-note">Career background for this person has not been researched yet.
        It will be filled in by the next person-research wave; in the meantime anything you write in
        <b>Prior Background</b> or <b>Notes / Facts</b> on the People sheet shows up here.</div>
      </div>
      <div>
        <div class="side-block">
          <h4>Company</h4>
          <p style="margin:0 0 6px; font-size:13px;"><b>{esc(v['name'])}</b></p>
          <p style="margin:0 0 6px; font-size:13px;"><a href="{dash_href(v['slug'])}" style="color:var(--steel);">White page &rarr;</a></p>
          <p style="margin:0; font-size:13px;"><a href="{v['website']}" target="_blank" rel="noopener" style="color:var(--steel);">{esc(v['website'].replace('https://', ''))} &#8599;</a></p>
        </div>
        <div class="private-block" id="private">
          <h4>Your notes</h4>
          <p style="font-size:12.5px; color:var(--ink-3); margin:0;">
            Nothing on file. Fill in this person's row on the <b>People</b> sheet &mdash;
            LinkedIn, email, phone, how you know them &mdash; and it appears here.</p>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">02</span><h2>Your notes</h2></div>
    <div id="ownnotes"><div class="qual-note">Nothing on file.</div></div>
  </section>
"""

            body = f"""
  <div id="gip-loadbar" class="loadbar">Reading gip-tracker.xlsx\u2026</div>

  <section>
    <div class="sec-head"><span class="sec-num">01</span><h2>Profile</h2></div>
    <div class="pdetail">
      <div>
        <div class="pcard-head" style="margin-bottom:16px;">
          <div class="mono">{ini}</div>
          <div>
            <div class="pcard-co">{esc(v['name'])}</div>
            <div class="pcard-name" style="font-size:20px;">{esc(p['name'])} {badge}</div>
            <div class="pcard-role" style="font-size:13px;">{esc(title)}</div>
          </div>
        </div>
        <div class="btn-row" style="margin-bottom:16px;">
          <a class="btn" href="contact-{pid}-one-sheet.pdf" download>Download white paper (PDF) &darr;</a>
          <a class="btn secondary" href="{dash_href(v['slug'])}">{esc(v['name'])} white page &rarr;</a>
          <a class="btn secondary" href="people.html?vendor={v['slug']}">All {esc(v['name'])} contacts</a>
        </div>
{bio_block}
  <footer>
    Public professional information only \u2014 role, career, education, published sources.
    No personal contact details are ever researched or stored here; those live only in
    <code>gip-tracker.xlsx</code> on your machine.
  </footer>
"""
            scripts = """<script>
(function(){
  var ID = %s;
  GIP.ready(function(d){
    var p = d.peopleById[ID];
    if(!p) return;
    var rows=[];
    if(p.linkedin) rows.push('<p><b>LinkedIn:</b> <a href="'+GIP.esc(p.linkedin)+'" target="_blank" rel="noopener" style="color:var(--steel);">Profile &#8599;</a></p>');
    if(p.email) rows.push('<p><b>Email:</b> <a href="mailto:'+GIP.esc(p.email)+'" style="color:var(--steel);">'+GIP.esc(p.email)+'</a></p>');
    if(p.phone) rows.push('<p><b>Phone:</b> '+GIP.esc(p.phone)+'</p>');
    if(p.mobile) rows.push('<p><b>Mobile:</b> '+GIP.esc(p.mobile)+'</p>');
    if(p.preferred) rows.push('<p><b>Prefers:</b> '+GIP.esc(p.preferred)+'</p>');
    if(p.assistant) rows.push('<p><b>Assistant:</b> '+GIP.esc(p.assistant)+'</p>');
    if(p.location) rows.push('<p><b>Location:</b> '+GIP.esc(p.location)+'</p>');
    if(p.since) rows.push('<p><b>In role since:</b> '+GIP.esc(p.since)+'</p>');
    if(p.owner) rows.push('<p><b>Relationship owner:</b> '+GIP.esc(p.owner)+'</p>');
    if(p.lastContact) rows.push('<p><b>Last contact:</b> '+GIP.esc(p.lastContact)+'</p>');
    if(p.nextTouch) rows.push('<p><b>Next touch:</b> '+GIP.esc(p.nextTouch)
        +(p.nextTouchDue ? ' <span style="color:var(--ink-3);">('+GIP.esc(p.nextTouchDue)+')</span>' : '')+'</p>');
    if(rows.length){
      document.getElementById("private").innerHTML='<h4>Your notes</h4><div class="fact-list">'+rows.join("")+'</div>';
    }
    var extra=[];
    if(p.howWeKnow) extra.push('<div class="subhead">How we know them</div><div class="qual-note">'+GIP.esc(p.howWeKnow)+'</div>');
    if(p.whereMet) extra.push('<div class="subhead" style="margin-top:16px;">Where we met</div><div class="qual-note">'+GIP.esc(p.whereMet)+'</div>');
    if(p.meetingFacts) extra.push('<div class="subhead" style="margin-top:16px;">From meetings</div><div class="qual-note">'+GIP.esc(p.meetingFacts)+'</div>');
    if(p.notes) extra.push('<div class="subhead" style="margin-top:16px;">Notes</div><div class="qual-note">'+GIP.esc(p.notes)+'</div>');
    if(p.background && document.getElementById("bio")) document.getElementById("bio").innerHTML = GIP.esc(p.background);
    if(extra.length) document.getElementById("ownnotes").innerHTML=extra.join("");
  });
})();
</script>""" % json.dumps(pid)

            html = shell(f"{p['name']} \u2014 {v['name']}",
                         f"CONTACT PROFILE &nbsp;\u00b7&nbsp; {esc(v['name']).upper()}",
                         esc(p["name"]), esc(title),
                         body, None,
                         back=("people.html", "All contacts"),
                         scripts=scripts)
            open(os.path.join(ROOT, f"person-{pid}.html"), "w").write(html)
            n += 1
    return n


# =====================================================================
#  Stub white pages for vendors awaiting research
# =====================================================================
def build_stubs():
    n = 0
    for v in VENDORS:
        if v["research_status"] == "full":
            continue
        tags = "".join(f'<span class="chip">{esc(t)}</span>' for t in v["tags"])
        body = f"""
  <div id="gip-loadbar" class="loadbar">Reading gip-tracker.xlsx…</div>

  <section>
    <div class="sec-head"><span class="sec-num">01</span><h2>Company snapshot</h2></div>
    <div class="snap-grid">
      <div>
        <p>{esc(v['description'])}</p>
        <div class="callout"><b>Deep research pending.</b> This page carries only what is known with
        certainty: what the company does, where to find it, and how it's categorised. Revenue, headcount,
        named customers, sourced use cases, competitive position, sentiment and named executives are
        deliberately blank rather than estimated &mdash; they get filled by the research pass for
        {esc(v['name'])}.</div>
      </div>
      <div>
        <div class="side-block">
          <h4>Key facts</h4>
          <p style="margin:0;"><b>Web:</b> <a href="{v['website']}" target="_blank" rel="noopener" style="color:var(--steel);">{esc(v['website'].replace('https://', ''))}</a>
          {' &nbsp;·&nbsp; <a href="' + v['linkedin'] + '" target="_blank" rel="noopener" style="color:var(--steel);">LinkedIn &#8599;</a>' if v['linkedin'] else ''}</p>
        </div>
        <div class="side-block">
          <h4>Categories</h4>
          <div class="chip-row">{tags}</div>
        </div>
        <div class="side-block">
          <h4>Key people</h4>
          <div class="qual-note" style="font-size:12.5px;">Not yet researched. Anyone you add on the
          <b>People</b> sheet for {esc(v['name'])} appears below.</div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">02</span><h2>GIP engagement</h2></div>
    <div class="sec-note">Live from your tracker workbook.</div>
    <div class="gip-panel" id="gip-panel" data-vendor="{esc(v['name'])}"></div>
  </section>

  <section>
    <div class="sec-head"><span class="sec-num">03</span><h2>Contacts</h2></div>
    <div class="card-grid" id="gip-people"></div>
    <div id="nopeople" class="empty" style="display:none;"><b>No contacts on file</b>
      Add rows for {esc(v['name'])} on the People sheet.</div>
  </section>

  <footer>
    Research shell generated {BUILD_DATE}. Part of the
    <a href="index.html" style="color:var(--steel);">GIP vendor &amp; technology tracker</a>.
  </footer>
"""
        html = shell(f"{v['name']} — Vendor Profile",
                     f"VENDOR PROFILE &nbsp;·&nbsp; RESEARCH PENDING",
                     f'<a href="{v["website"]}" target="_blank" rel="noopener" style="color:inherit; text-decoration:none;">{esc(v["name"])} &#8599;</a>',
                     esc(v["description"]),
                     body, None,
                     back=("index.html", "All vendors"),
                     scripts='<script src="app-data.js"></script>\n<script src="gip-panel.js"></script>')
        open(os.path.join(ROOT, f"{v['slug']}-dashboard.html"), "w").write(html)
        n += 1
    return n


if __name__ == "__main__":
    write_app_data()
    build_overview()
    build_tracker()
    build_scorecard()
    build_people_index()
    np_ = build_person_pages()
    ns = build_stubs()
    print(f"overview + tracker + scorecard + contacts; {np_} person pages; {ns} research-shell white pages")
