# -*- coding: utf-8 -*-
"""
Vendor data for the Physical AI / Industrial AI for Critical Infrastructure market landscape.
Each dict feeds both the HTML mini-dashboard and the one-page PDF for that vendor, mirroring
the section structure used on the Sand Technologies dashboard: Snapshot, Ratings, Use Cases
(each source-linked), Competitive Landscape, and Sentiment (customer / market / employee).
"""

VENDORS = [
    {
        "slug": "sand-technologies",
        "name": "Sand Technologies",
        "website": "https://www.sandtech.com",
        "linkedin": "https://www.linkedin.com/company/sand-technologies",
        "category": "Physical AI platform (infrastructure control)",
        "tagline": "\u201cPhysical AI\u201d operating system for critical infrastructure \u2014 water, energy, telecom, health &amp; government",
        "founded": "2023 (current form; ~10-yr consulting heritage; merged with ExploreAI, Feb 2024)",
        "hq": "Mauritius (registered HQ); engineering hubs: Silicon Valley, Paris, Romania, Latin America, Africa",
        "employees": "~500\u2013680 (est., sources vary)",
        "ownership": "Private; backed in part by the Bestseller Foundation; no reported funding round",
        "revenue": "$15\u201367M (3rd-party estimates only; not company-disclosed)",
        "revenue_short": "$15\u201367M (est.)",
        "offering": "Symmetri \u2014 a real-time \u201cPhysical AI\u201d control layer (Sense / Analyze / Act) that models physical assets and networks and can act on them directly, for water, energy, telecom, health and government operators.",
        "digital_twin": "Yes (live system model)",
        "genai": "Yes",
        "buyer": "Utility, telecom &amp; government operations leaders",
        "customers": ["AWS (Advanced Tier partner)", "GE", "JP Morgan", "Thames Water", "Telkomsel", "Cassava Technologies", "Compass UOL", "Bestseller A/S", "Stanbic Bank (Kenya)", "Tamara (Dubai)"],
        "people": [
            {"name": "Fred Swaniker", "title": "Founder &amp; CEO"},
            {"name": "Danai Mavunga", "title": "Chief Operating Officer"},
            {"name": "David Bratt", "title": "Chief Financial Officer"},
            {"name": "George Ionita", "title": "Chief Technology Officer"},
        ],
        "description": "Private Physical AI vendor with deep emerging-market delivery reach via its ALX talent pipeline; deployed in 18+ countries with a services-heavy, project-based model rather than disclosed SaaS metrics.",
        "position_note": "The category creator framing \u2014 \u201cPhysical AI\u201d as sensing, modeling and directly acting on infrastructure. Smallest and least capitalized name on this list; its edge is emerging-market reach, not platform scale.",
        "glassdoor": {"rating": "3.6", "reviews": "47", "recommend": "66%", "outlook": "60%", "ceo_approval": "n/a"},
        "use_cases": [
            {"sector": "Water utilities", "deployment": "Thames Water (UK) \u2014 predictive network management", "impact": "Vendor describes moving the utility from reactive to predictive management; no standalone quantified result published", "status": "Deployed", "source": "https://www.sandtech.com/water-utilities/"},
            {"sector": "Telecom", "deployment": "Telkomsel (Indonesia) network optimization + AWS \u201cAI-Driven Network Planner\u201d", "impact": "+8\u201315% data traffic, +5\u20138% coverage, $10\u201350M annual value \u2014 without new infrastructure", "status": "Deployed", "source": "https://www.sandtech.com/telecommunications/"},
            {"sector": "Health", "deployment": "Rural clinic network, Africa", "impact": "Connects thousands of rural clinics into one coordinated-care network serving millions of patients", "status": "Deployed", "source": "https://www.sandtech.com/health/"},
            {"sector": "Disaster response", "deployment": "Post-tornado city response \u2014 Symmetri damage-assessment layer", "impact": "~5,400 damaged structures mapped, ~$0.8B in estimated losses prioritized for recovery resources", "status": "Deployed", "source": "https://aws.amazon.com/marketplace/pp/prodview-ae2fh6326bbpi"},
        ],
        "sentiment_bull": [
            "High-profile founder (TIME 100, WEF Young Global Leader, TED Fellow) drives press and government access",
            "AWS Advanced Tier partner status broadens enterprise channel reach",
            "Deployments claimed across 18+ countries with \u201czero mission-critical failures\u201d (vendor claim, unaudited)",
        ],
        "sentiment_bear": [
            "Headcount down ~6% (6-mo) / ~9% (2-yr) per Simplify tracking, despite a growth narrative",
            "Revenue concentration in large infrastructure clients, which creates project-delay risk if deployments slip",
            "Analyst-rated C on Differentiation \u2014 crowded field vs. Palantir, C3.ai, Cognite, Bentley, AVEVA",
        ],
        "customer_sentiment": "No independent review presence: Sand Symmetri's AWS Marketplace listing shows zero submitted reviews, and there is no active G2/Capterra/TrustRadius profile. What exists is vendor-published case studies with metrics but no verbatim customer quotes.",
        "employee_sentiment": "Praise for mission, talent and pace of delivery; recurring complaints about frequent strategic pivots, an unclear product offering, and meeting load.",
        "gip_connection": "No direct connection found. Sand is privately held with no disclosed GIP investment, and none of Sand's named customers appear on GIP's own portfolio-company list (airports, ports, rail, data centers, water/waste and energy assets).",
        "blackrock_connection": "No equity or ownership connection found. There is a real indirect link worth flagging, though: Sand's flagship water-utilities case study customer, Thames Water, has BlackRock as one of the senior creditor bondholders (alongside Aberdeen, Elliott Management, Apollo, M&amp;G and Silver Point Capital) in the ~\u00a317B debt restructuring that is on track to hand ownership of Thames Water to its creditors. If that restructuring completes as proposed, BlackRock would become a part-owner of a Sand customer \u2014 a deal-contingent link, not a confirmed current relationship.",
        "has_full_dashboard": True,
    },
    {
        "slug": "palantir",
        "name": "Palantir Technologies",
        "website": "https://www.palantir.com",
        "linkedin": "https://www.linkedin.com/company/palantir-technologies",
        "category": "Enterprise &amp; government data-AI platform",
        "tagline": "The operating system for data-driven decisions across defense, intelligence and enterprise",
        "founded": "2003",
        "hq": "Denver, CO (relocated from Palo Alto; some 2026 reports cite a Miami-area office too)",
        "employees": "~4,400 (2025)",
        "ownership": "Public (Nasdaq: PLTR)",
        "revenue": "$4.48B (FY2025), up 56% YoY; FY2026 guidance raised to $7.65\u2013$7.66B",
        "revenue_short": "$4.48B (FY2025)",
        "offering": "Four core platforms: Gotham (defense/intelligence), Foundry (commercial enterprise data integration), Apollo (deployment infrastructure) and AIP (AI Platform, launched 2023) \u2014 lets organizations deploy LLMs directly against their own operational data.",
        "digital_twin": "Partial (ontology-based data model, not a physical digital twin)",
        "genai": "Yes \u2014 AIP is the fastest-growing product line",
        "buyer": "Government/defense agencies and enterprise data &amp; ops leaders",
        "customers": ["CIA", "U.S. Army", "NHS England", "Airbus", "Ferrari", "Morgan Stanley", "Merck KGaA", "PG&amp;E"],
        "people": [
            {"name": "Alex Karp", "title": "Co-Founder &amp; CEO"},
            {"name": "Stephen Cohen", "title": "Co-Founder &amp; President"},
            {"name": "Peter Thiel", "title": "Co-Founder &amp; Chairman of the Board"},
            {"name": "Shyam Sankar", "title": "Chief Technology Officer"},
        ],
        "description": "The best-capitalized, fastest-growing name in this market by far \u2014 GAAP-profitable, ~56% revenue growth, and a fast-scaling \u201cAIP Bootcamp\u201d go-to-market motion pulling U.S. commercial revenue up over 130% YoY.",
        "position_note": "Broadest platform ambition and by far the largest balance sheet in this market. Closest comparable to Sand on category ambition (\u201coperating system\u201d framing) but built for data/decisions generally, not physical-infrastructure control specifically.",
        "glassdoor": {"rating": "3.8", "reviews": "889", "recommend": "66%", "outlook": "76%", "ceo_approval": "74%"},
        "use_cases": [
            {"sector": "Aerospace / manufacturing", "deployment": "Airbus \u2014 Skywise platform on Foundry", "impact": "+33% production increase on the A350 aircraft line; Skywise now improves decision-making at 100+ airlines", "status": "Deployed", "source": "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RW1nTi3"},
            {"sector": "Energy", "deployment": "Oil &amp; gas major \u2014 Foundry data integration", "impact": "Scanned 300+ SAP data sets across 5 legacy ERPs; unlocked ~$50M working capital in 2 weeks; identified 30k additional barrels/day, ~$1B additional opportunity", "status": "Deployed", "source": "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RW1nTi3"},
            {"sector": "Utilities", "deployment": "PG&amp;E \u2014 wildfire risk &amp; grid optimization", "impact": "8\u201310 billion data points processed daily to inform wildfire mitigation and grid decisions for 16 million customers", "status": "Deployed", "source": "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RW1nTi3"},
            {"sector": "Financial services", "deployment": "Global commercial bank \u2014 Foundry + AIP", "impact": "1,200+ data sources integrated; $65M+ additional revenue unlocked across 100 use cases and 15,000+ users", "status": "Deployed", "source": "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RW1nTi3"},
            {"sector": "Healthcare / government", "deployment": "NHS England \u2014 Federated Data Platform", "impact": "\u00a3330M contract; described as providing a \u201csingle source of truth\u201d for the UK's largest operational data integration exercise", "status": "Deployed", "source": "https://digitalstrategy.rsm.nl/2025/09/17/palantir-data-integration-or-digital-dependency/"},
        ],
        "sentiment_bull": [
            "Revenue growth accelerating \u2014 56% YoY in FY2025, guiding to 61%+ for FY2026, GAAP-profitable since 2023",
            "AIP Bootcamp model converts roughly 75% of prospects into signed contracts; U.S. commercial revenue up 130%+ YoY",
            "S&amp;P 500 inclusion (Sept 2024) and a fast-growing roster of blue-chip commercial reference customers",
        ],
        "sentiment_bear": [
            "Valuation is priced for perfection \u2014 among the most expensive large-cap software multiples in the market",
            "Deep ties to defense/intelligence work draw recurring criticism (ACLU and others) over predictive-policing use of Gotham",
            "Customer lock-in risk is real: once operations run on Foundry's ontology, switching costs are very high",
        ],
        "customer_sentiment": "Strong, vocal reference customers (BP, PG&amp;E, NHS) appear repeatedly in Palantir's own case studies and at its AIPCon customer events, but independent third-party review volume (G2/Gartner Peer Insights) is thin relative to its market cap \u2014 most public sentiment is analyst/investor commentary rather than software-buyer reviews.",
        "employee_sentiment": "High talent density and real-world mission impact are the most-cited positives; work-life balance is the most-cited negative (2.8/5 on that sub-metric) alongside opaque post-cliff compensation communication.",
        "gip_connection": "No named GIP portfolio company was confirmed as a Palantir customer in available sources. The sectoral overlap is real \u2014 Palantir markets Foundry/AIP explicitly for \u201ccritical infrastructure,\u201d construction (named partners McCarthy and Kiewit), and government, territory that includes GIP-style assets like airports, ports and utilities \u2014 but no specific GIP-owned asset was confirmed as a live deployment.",
        "blackrock_connection": "Confirmed and substantial, but passive: BlackRock is one of Palantir's largest institutional shareholders, holding roughly 5.5%\u20138.7% of shares outstanding across recent 13G/13F filings (an ~$19.9B position as of mid-2026, per TIKR/SEC data). This is standard index-fund ownership \u2014 BlackRock holds comparable stakes in thousands of public companies \u2014 not a commercial or operating partnership.",
    },
    {
        "slug": "c3ai",
        "name": "C3.ai",
        "website": "https://c3.ai",
        "linkedin": "https://www.linkedin.com/company/c3-ai",
        "category": "Enterprise AI application platform",
        "tagline": "Enterprise AI applications for manufacturing, energy, defense and financial services",
        "founded": "2009 (as C3 Energy / C3 IoT; renamed C3.ai in 2019)",
        "hq": "Redwood City, CA",
        "employees": "~1,000\u20131,180",
        "ownership": "Public (NYSE: AI)",
        "revenue": "$389.1M (FY2025), up 25% YoY; quarterly revenue has since decelerated (Q4 FY2026: $51.6M)",
        "revenue_short": "$389M (FY2025)",
        "offering": "C3 Agentic AI Platform (end-to-end build/deploy/operate environment) plus 40+ prebuilt, industry-specific Enterprise AI applications and C3 Generative AI tools.",
        "digital_twin": "No",
        "genai": "Yes",
        "buyer": "Industrial, defense and financial-services IT &amp; operations leaders",
        "customers": ["Shell", "Bank of America", "U.S. Air Force", "U.S. Army", "Baker Hughes", "Cargill", "Koch Industries", "AMD"],
        "people": [
            {"name": "Thomas M. Siebel", "title": "Founder, Chairman &amp; Chief Executive Officer"},
            {"name": "Stephen Ehikian", "title": "President"},
            {"name": "Edward Abbo", "title": "Chief Technology Officer"},
        ],
        "description": "Public but smaller and less differentiated than Palantir, with real recent strain: revenue growth has decelerated sharply, founder Tom Siebel resumed the CEO role in May 2026 after a health-related leadership change, and Glassdoor sentiment has fallen from 3.1 to 2.9 over the past year.",
        "position_note": "Closest comparable to Sand on \u201cvertical AI applications\u201d positioning, but sells software licenses/subscriptions rather than the services-heavy delivery model Sand uses \u2014 and is currently the most stressed name on this list financially and organizationally.",
        "glassdoor": {"rating": "2.9", "reviews": "825", "recommend": "40%", "outlook": "28%", "ceo_approval": "n/a"},
        "use_cases": [
            {"sector": "Energy (oil &amp; gas)", "deployment": "Shell \u2014 predictive maintenance at scale", "impact": "Scaled AI predictive maintenance to 10,000 pieces of equipment", "status": "Deployed", "source": "https://c3.ai/news?page=5"},
            {"sector": "Energy (JV)", "deployment": "Baker Hughes \u2014 industrial asset management JV", "impact": "6-year, $495M minimum commitment (through June 2025); Baker Hughes holds an equity stake and a board seat", "status": "Deployed", "source": "https://c3ai.gcs-web.com/static-files/5b6aea30-651c-4991-aafd-1bcd0fb2c4d9"},
            {"sector": "Chemicals", "deployment": "LyondellBasell \u2014 five-year expanded enterprise AI contract", "impact": "Contract expansion signed to accelerate enterprise AI deployment across operations", "status": "Deployed", "source": "https://c3.ai/news?page=5"},
            {"sector": "Defense", "deployment": "Missile Defense Agency \u2014 modeling &amp; simulation contract", "impact": "Awarded contract for AI-based modeling and simulation work", "status": "Deployed", "source": "https://c3.ai/news?page=5"},
        ],
        "sentiment_bull": [
            "Broad partner ecosystem \u2014 six-year Microsoft Azure partnership, plus AWS and Google Cloud alliances",
            "Federal/defense bookings grew 134% YoY in a recent quarter as government AI demand accelerates",
            "40+ prebuilt industry applications shorten deployment time versus building from scratch",
        ],
        "sentiment_bear": [
            "Customer concentration risk: Baker Hughes has historically been ~20\u201330% of revenue via a JV with renegotiated minimums",
            "Quarterly revenue has decelerated markedly (Q3 FY2025 from $98.8M in Q3 FY2025 to $51.6M in Q4 FY2026, per filings)",
            "Founder Tom Siebel stepped back for health reasons in Sept 2025, then resumed the CEO role in May 2026 \u2014 real leadership turbulence",
            "One recent employee review (unverified, anecdotal) described revenue \u201cplummeting\u201d and headcount falling sharply \u2014 directionally consistent with the filed revenue deceleration but not independently confirmed at that magnitude",
        ],
        "customer_sentiment": "Public case studies (Shell, Baker Hughes, LyondellBasell) show real deployed scale, but G2/Gartner Peer Insights review volume is modest for a public company of this size, and the JV-heavy customer base makes independent reference-checking harder than for a typical SaaS vendor.",
        "employee_sentiment": "Recent reviews cite a sharp deterioration \u2014 \u201csinking ship\u201d language and reports of aggressive attrition \u2014 a marked reversal from C3.ai's earlier \u201chighest-rated cloud company to work for\u201d recognition (Battery Ventures/Glassdoor, ~2021).",
        "gip_connection": "No connection found. None of C3.ai's named customers (Shell, Baker Hughes, Bank of America, U.S. Air Force/Army, Cargill, Koch) are GIP portfolio companies.",
        "blackrock_connection": "Confirmed passive ownership \u2014 6.8% of shares outstanding per BlackRock's April 2026 Schedule 13G/A filing, its largest disclosed institutional holder after Vanguard (6.1%) and founder Thomas Siebel's combined family/trust stakes (~15%+).",
    },
    {
        "slug": "cognite",
        "name": "Cognite",
        "website": "https://www.cognite.com",
        "linkedin": "https://www.linkedin.com/company/cognitedata",
        "category": "Industrial data &amp; digital-twin platform",
        "tagline": "Industrial-grade AI platform turning operational data into a unified, contextualized foundation",
        "founded": "2016/2017 (Oslo, Norway)",
        "hq": "Oslo, Norway / Austin, TX",
        "employees": "~800",
        "ownership": "Being acquired by Schneider Electric for $3.1B all-cash (announced June 30, 2026), folding into AVEVA",
        "revenue": "$170M+ (2025), up 36% in ARR bookings",
        "revenue_short": "$170M+ (2025)",
        "offering": "Cognite Data Fusion (unified industrial data model + knowledge graph) and Atlas AI (generative/agentic AI for industrial workflows), covering plant operations, asset management and engineering.",
        "digital_twin": "Yes (core capability)",
        "genai": "Yes (Atlas AI)",
        "buyer": "Industrial/asset-intensive operations &amp; engineering leaders",
        "customers": ["Saudi Aramco", "Aker BP", "Aker ASA portfolio companies", "large energy &amp; process-industry operators"],
        "people": [
            {"name": "Girish Rishi", "title": "Chairman &amp; Chief Executive Officer"},
            {"name": "John Markus Lervik", "title": "Co-Founder &amp; Chief Strategy Officer"},
            {"name": "Geir Engdahl", "title": "Co-Founder &amp; Chief Technology Officer, AI"},
        ],
        "description": "The clearest signal of where this market is heading: an independent industrial-AI platform just sold to a strategic incumbent (Schneider Electric) for 18x revenue, consolidating into AVEVA.",
        "position_note": "Closest comparable to Sand on the digital-twin/industrial-data angle specifically. Its $3.1B exit is the reference point for what a well-executed independent player in this space can be worth.",
        "glassdoor": {"rating": "3.2", "reviews": "169", "recommend": "n/a", "outlook": "n/a", "ceo_approval": "n/a"},
        "use_cases": [
            {"sector": "Oil &amp; gas", "deployment": "Aker BP \u2014 maintenance, safety &amp; production optimization on Cognite Data Fusion", "impact": "Faster condition monitoring, visualized safety risk factors, and hybrid ML-based production optimization across 20+ published case studies", "status": "Deployed", "source": "https://www.casestudies.com/company/cognite"},
            {"sector": "Cross-industry (Forrester TEI study)", "deployment": "Composite heavy-asset organization \u2014 Cognite Data Fusion", "impact": "$21.6M net value added, 400% ROI, reduced downtime and improved maintenance planning (Forrester Consulting, commissioned study)", "status": "Deployed", "source": "https://www.cognite.com/en/press-release/independent-study-finds-asset-heavy-organizations-can-expect-21.6m-in-value-after-adopting-cognite-data-fusion"},
            {"sector": "OEM / ISV tooling", "deployment": "Cognite Embedded \u2014 white-labeled for equipment makers and software vendors", "impact": "2\u20133x faster product development, 80% lower total cost of ownership for OEM/ISV partners (e.g., Rockwell Automation's FactoryTalk DataMosaix)", "status": "Deployed", "source": "https://www.cognite.com/en/newsroom"},
        ],
        "sentiment_bull": [
            "Just validated at a $3.1B exit (18x 2025 revenue) by a top-tier strategic acquirer, Schneider Electric",
            "Saudi Aramco is both a long-time digitalization partner and an equity investor (7.4% stake, 2022)",
            "Rated a \u201cLeader\u201d by S&amp;P Global among 20 evaluated digital-twin vendors",
        ],
        "sentiment_bear": [
            "About to lose independence entirely \u2014 folding into AVEVA under Schneider Electric, with integration risk for customers and staff",
            "Glassdoor sample size is thin (169 reviews) for a company this size, limiting confidence in the 3.2 rating",
            "Post-acquisition roadmap and brand continuity are open questions as of the deal announcement",
        ],
        "customer_sentiment": "Extensive, detailed public case studies (55+ published, many with Aker BP) and a Forrester-commissioned ROI study showing 400% ROI \u2014 among the more substantively documented customer track records on this list, though commissioned studies carry an inherent vendor bias.",
        "employee_sentiment": "Limited review volume; available reviews are moderately positive but not enough data to draw a confident trend line before the Schneider Electric integration begins.",
        "gip_connection": "No connection found. Cognite's investor base (Aker ASA, TCV, Accel, Saudi Aramco) has no disclosed GIP tie, and no GIP portfolio company appears among its named customers (Aker BP and others).",
        "blackrock_connection": "No direct stake in Cognite today. Indirect exposure is coming: once Schneider Electric's ~$3.1B acquisition of Cognite closes, Cognite becomes part of a company where BlackRock is the largest shareholder (7.93% of Schneider Electric, per recent filings) \u2014 passive ownership at one remove, not a strategic relationship.",
    },
    {
        "slug": "bentley-systems",
        "name": "Bentley Systems",
        "website": "https://www.bentley.com",
        "linkedin": "https://www.linkedin.com/company/bentley-systems",
        "category": "Infrastructure engineering software",
        "tagline": "The infrastructure engineering software company \u2014 design, construction and operations",
        "founded": "1984",
        "hq": "Exton, PA",
        "employees": "~5,500\u20135,800",
        "ownership": "Public (Nasdaq: BSY); Bentley family retains majority voting control via dual-class shares",
        "revenue": "$1.5B (FY2025), up 11% YoY; 24.1% operating margin",
        "revenue_short": "$1.5B (FY2025)",
        "offering": "iTwin Platform (infrastructure digital twins), AssetWise (asset/network performance), ProjectWise (project delivery), SYNCHRO (construction management) and MicroStation-based design tools; 41,000+ accounts in ~195 countries.",
        "digital_twin": "Yes (iTwin is a core platform)",
        "genai": "Emerging (AI features layered into iTwin/AssetWise)",
        "buyer": "Civil/structural engineers and infrastructure asset owners",
        "customers": ["HNTB", "JMT", "Hatch Ltd.", "SPL Powerlines UK", "government transportation agencies", "electric utilities"],
        "people": [
            {"name": "Nicholas Cumins", "title": "Chief Executive Officer"},
            {"name": "Greg Bentley", "title": "Executive Chairman (co-founder)"},
        ],
        "description": "Profitable, public infrastructure-software incumbent with a 40-year design-through-operations footprint \u2014 the closest thing to an \u201cestablishment\u201d peer for Sand's water/energy/transport verticals, and the best-rated employer on this list by its own staff.",
        "position_note": "Strong overlap with Sand on infrastructure asset lifecycle and digital twins, but Bentley's roots are in engineering design software (CAD-first) rather than real-time operational AI control.",
        "glassdoor": {"rating": "3.9", "reviews": "1,424", "recommend": "76%", "outlook": "69%", "ceo_approval": "88%"},
        "use_cases": [
            {"sector": "Rail / transit", "deployment": "WSP \u2014 Melbourne rail network project using ProjectWise, SYNCHRO &amp; iTwin", "impact": "Modeling time reduced 60%, productivity increased 25%, carbon footprint reduced 30%", "status": "Deployed", "source": "https://www.bentley.com/news/bentley-systems-recognizes-the-year-in-infrastructure-2023-as-groundbreaking-for-infrastructure-intelligence/2/"},
            {"sector": "Water utilities", "deployment": "Singapore's national water agency (PUB) \u2014 digital twin + AI leak detection", "impact": "Near-real-time detection and localization of water-supply anomalies and leaks via high-fidelity digital twin and hydraulic modeling", "status": "Deployed", "source": "https://www.bentley.com/news/"},
            {"sector": "Bridges / dams", "deployment": "AssetWise bridge &amp; dam monitoring \u2014 drone + iTwin Capture digital twins", "impact": "Converts physical inspections into remote, AI/ML-assisted defect detection, avoiding costly and hazardous site visits", "status": "Deployed", "source": "https://www.bentley.com/software/assetwise/"},
        ],
        "sentiment_bull": [
            "Best employee sentiment on this list: 3.9/5 Glassdoor, 76% recommend, 88% CEO approval",
            "Profitable at scale \u2014 24.1% operating margin, $538M operating cash flow in FY2025",
            "41,000+ accounts across 194 countries gives it the broadest installed base of any name here",
        ],
        "sentiment_bear": [
            "AI narrative is \u201cemerging,\u201d not core \u2014 lags Palantir/C3.ai/Cognite on generative and agentic AI maturity",
            "Dual-class share structure keeps the founding family in control, limiting activist or outside investor influence",
            "CAD/engineering-design heritage means real-time operational AI control is a newer, less-proven muscle than for Sand or Cognite",
        ],
        "customer_sentiment": "Deep bench of quantified, named case studies (WSP, Singapore PUB) published directly by Bentley, plus a large installed base that generates steady independent commentary in AEC industry press \u2014 among the more substantively evidenced customer track records on this list.",
        "employee_sentiment": "Consistently positive: strong culture and work-life balance are the most-cited pros; below-market pay in some regions and a perceived \u201cslow transformation\u201d pace are the most-cited cons.",
        "gip_connection": "No named GIP portfolio company was confirmed as a Bentley customer, though Bentley's customer base of government transportation agencies and infrastructure owner-operators plausibly overlaps with GIP-owned airports, ports and rail (Bentley's software is near-ubiquitous in civil infrastructure engineering) \u2014 no specific deployment was confirmed in available sources.",
        "blackrock_connection": "Confirmed \u2014 5.4% of shares outstanding per a July 2026 Schedule 13G/A, making BlackRock Bentley's largest institutional holder outside the founding Bentley family, which retains majority voting control via dual-class shares.",
    },
    {
        "slug": "aveva",
        "name": "AVEVA",
        "website": "https://www.aveva.com",
        "linkedin": "https://www.linkedin.com/company/aveva",
        "category": "Industrial software / digital-twin suite",
        "tagline": "Industrial software for the design, operation and optimization of industrial assets",
        "founded": "1967 (Cambridge, UK)",
        "hq": "Cambridge, UK",
        "employees": "~6,500",
        "ownership": "Wholly owned subsidiary of Schneider Electric since Jan 2023 (~$11.6B acquisition); no longer separately listed",
        "revenue": "Not separately disclosed post-acquisition (last standalone: ~$1.95B, FY2023)",
        "revenue_short": "Not disclosed",
        "offering": "CONNECT (industrial intelligence platform), PI System (real-time operational data), E3D Design (3D plant design), Unified Engineering, and the AVEVA Industrial AI Assistant \u2014 now absorbing Cognite's Data Fusion and Atlas AI as well.",
        "digital_twin": "Yes (extensive, across engineering and operations)",
        "genai": "Yes (Industrial AI Assistant)",
        "buyer": "Process/manufacturing engineering and operations leaders",
        "customers": ["Shell", "BP", "BASF", "Starbucks", "PETRONAS", "20 of the top 20 global energy companies (per AVEVA)"],
        "people": [
            {"name": "Caspar Herzberg", "title": "Chief Executive Officer"},
            {"name": "Peter Herweck", "title": "Chairperson (former CEO, Schneider Electric)"},
        ],
        "description": "No longer an independent company to evaluate on its own financials \u2014 AVEVA is now the industrial-software arm of Schneider Electric, and is about to absorb Cognite too, becoming the most consolidated platform on this list.",
        "position_note": "Strong digital-twin overlap with Sand, but operating as part of a much larger industrial conglomerate with hardware, energy management and automation businesses behind it.",
        "glassdoor": {"rating": "4.0", "reviews": "1,042", "recommend": "78%", "outlook": "67%", "ceo_approval": "73%"},
        "use_cases": [
            {"sector": "Oil &amp; gas", "deployment": "PETRONAS \u2014 AVEVA Predictive Analytics + PI System on rotating equipment", "impact": "Saved $17.4M in year one (51 warnings, 12 high-risk), 14x ROI, expanded to 10 new cloud-connected sites", "status": "Deployed", "source": "https://www.aveva.com/content/dam/aveva/documents/perspectives/success-stories/SuccessStory_AVEVA_PETRONAS_21-10-v1.pdf.coredownload.inline.pdf"},
            {"sector": "Chemicals / manufacturing", "deployment": "BASF \u2014 Smart Manufacturing program", "impact": "Deployed Enterprise Asset Performance Management with AR and predictive maintenance to improve asset availability and workforce efficiency", "status": "Deployed", "source": "https://www.automation.com/article/aveva-to-help-basf-accelerate-smart-manufacturing"},
            {"sector": "Energy (power)", "deployment": "Saudi Aramco \u2014 power optimization &amp; cogeneration efficiency advisory platform", "impact": "65% reduction in emissions, 48% reduction in maintenance costs, 23% increase in mean time between failures (MTBF)", "status": "Deployed", "source": "https://events.aveva.com/aw-2025/session/2892202/saudi-aramco-accelerating-sustainability-digital-advisory-platform-for-power-optimization-and-cogeneration-efficiency"},
        ],
        "sentiment_bull": [
            "Strongest employee Glassdoor rating among the industrial-software incumbents (4.0/5, 78% recommend)",
            "Concrete, audited-style ROI case studies (PETRONAS 14x ROI) with named Fortune 500 customers",
            "Backed by Schneider Electric's global reach and about to absorb Cognite's technology and talent",
        ],
        "sentiment_bear": [
            "No longer independently evaluable \u2014 standalone financials haven't been disclosed since the 2023 acquisition",
            "Employee reviews explicitly flag uncertainty about further internal consolidation under Schneider",
            "Integrating Cognite adds real near-term execution risk on top of the existing Schneider integration",
        ],
        "customer_sentiment": "Well-documented, quantified case studies (PETRONAS, Saudi Aramco, BASF) and solid third-party product ratings (Gartner Peer Insights ~4.1\u20134.4 for PI System) \u2014 one of the more substantively evidenced customer records on this list.",
        "employee_sentiment": "Generally positive on work-life balance and colleagues; the most-repeated concern is uncertainty about Schneider Electric's long-term integration plans for the brand and team.",
        "gip_connection": "No named GIP portfolio company was confirmed as an AVEVA customer. AVEVA does sell a purpose-built \u201cUnified Operations Center for Data Centers\u201d product directly relevant to GIP's CyrusOne data-center holdings, but no confirmed CyrusOne\u2013AVEVA relationship was found.",
        "blackrock_connection": "The clearest indirect link in this set: AVEVA's parent, Schneider Electric, has BlackRock as its largest shareholder at 7.93% of shares outstanding (per recent filings). AVEVA itself hasn't been separately listed since the 2023 acquisition, so this exposure flows entirely through Schneider's cap table.",
    },
    {
        "slug": "ibm-watsonx",
        "name": "IBM watsonx",
        "website": "https://www.ibm.com/watsonx",
        "linkedin": "https://www.linkedin.com/company/ibm",
        "category": "Enterprise AI &amp; data platform",
        "tagline": "IBM's enterprise AI and data platform for building, deploying and governing AI at scale",
        "founded": "2023 (platform launch); IBM itself founded 1911",
        "hq": "Armonk, NY (IBM corporate HQ)",
        "employees": "~300,000 (IBM overall; watsonx-specific headcount not disclosed)",
        "ownership": "Product line of IBM (public, NYSE: IBM)",
        "revenue": "Not separately disclosed (IBM total revenue ~$67.5B)",
        "revenue_short": "Not disclosed",
        "offering": "watsonx.ai (foundation-model studio), watsonx.data (data lakehouse) and watsonx.governance (AI lifecycle/risk/compliance), built around IBM's Granite models plus open-source and third-party models.",
        "digital_twin": "No",
        "genai": "Yes (core focus)",
        "buyer": "Enterprise IT and AI leaders, especially in regulated industries",
        "customers": ["SAP", "NASA", "Wix", "NatWest", "Cr\u00e9dit Mutuel", "Etisalat by e&amp;"],
        "people": [
            {"name": "Arvind Krishna", "title": "Chairman &amp; CEO, IBM"},
            {"name": "Rob Thomas", "title": "Senior VP, Software &amp; Chief Commercial Officer"},
        ],
        "description": "A governance-first enterprise AI platform riding IBM's existing enterprise relationships rather than a vertical infrastructure play \u2014 the most horizontal (industry-agnostic) offering on this list.",
        "position_note": "Overlaps with Sand mainly on AI governance and enterprise deployment discipline, not on physical-infrastructure control; IBM's brand and balance sheet dwarf every other name here except Siemens.",
        "glassdoor": {"rating": "3.9", "reviews": "107,000+", "recommend": "78%", "outlook": "68%", "ceo_approval": "77%"},
        "use_cases": [
            {"sector": "Banking", "deployment": "NatWest \u2014 \u201cCora\u201d virtual assistant evolved with watsonx/Watson AI", "impact": "+20% customer Net Promoter Score (NPS), \u201310% call duration", "status": "Deployed", "source": "https://www.ibm.com/case-studies/natwest-group-watson"},
            {"sector": "IT services (SMB)", "deployment": "Barr\u00e9 Technologies \u2014 watsonx-powered document/invoice automation", "impact": "+30% productivity, 1,380 hours/year saved for a 50-person team, ROI recovered in 13 months", "status": "Deployed", "source": "https://www.cuspera.com/products/ibm-watsonx-assistant-x-19743/customer-story"},
            {"sector": "Banking", "deployment": "Cr\u00e9dit Mutuel Alliance F\u00e9d\u00e9rale \u2014 watsonx.ai custom AI solutions", "impact": "Bank serving 30M+ customers building tailored generative-AI solutions on watsonx.ai (qualitative case study, no published metric)", "status": "Deployed", "source": "https://www.ibm.com/es-es/case-studies/credit-mutuel-alliance-federale-client-quote"},
        ],
        "sentiment_bull": [
            "Rides IBM's existing enterprise relationships and regulated-industry trust \u2014 fastest path to enterprise-grade governance",
            "Model flexibility (IBM Granite + open-source + third-party) plus on-prem/hybrid deployment for strict compliance needs",
            "Praised by practitioners for reducing friction from experimentation to production with built-in governance and audit trails",
        ],
        "sentiment_bear": [
            "Some internal reviewers note limited hands-on usage \u2014 one employee described watsonx training as done \u201cfor the sake of training\u201d with little real deployment exposure",
            "Complex initial user experience flagged by Gartner Peer Insights reviewers, especially for less technical teams",
            "No physical-infrastructure specialization \u2014 competes as a horizontal platform against nimbler vertical specialists",
        ],
        "customer_sentiment": "Gartner Peer Insights reviews for watsonx.ai are mixed-to-positive (governance and flexibility praised; UX complexity criticized); IBM's own published case studies (NatWest, Barr\u00e9) show real quantified wins, though as with any vendor-published study, treat as illustrative rather than independently audited.",
        "employee_sentiment": "IBM overall skews positive (3.9/5, 78% recommend) but is a 300,000-person company \u2014 the rating reflects IBM broadly, not the watsonx team specifically; some reviewers describe limited internal exposure to the product itself.",
        "gip_connection": "No connection found. IBM's enterprise client base is broad enough that overlap with a GIP portfolio company is plausible, but no specific relationship was confirmed in available sources.",
        "blackrock_connection": "Confirmed passive ownership \u2014 BlackRock holds a ~$18.8B stake in IBM (77.6M shares as of Q1 2026), its largest institutional holder ahead of Vanguard and State Street.",
    },
    {
        "slug": "honeywell-forge",
        "name": "Honeywell Forge",
        "website": "https://www.honeywell.com/us/en/software/forge",
        "linkedin": "https://www.linkedin.com/company/honeywell",
        "category": "Industrial IoT / AI software platform",
        "tagline": "Hardware-agnostic, open-architecture platform for real-time, AI-enabled operational insight",
        "founded": "Platform launched ~2018; Honeywell itself founded 1906",
        "hq": "Charlotte, NC",
        "employees": "Not disclosed separately; Honeywell overall is mid-scale industrial conglomerate (undergoing 2025\u201326 breakup)",
        "ownership": "Product line of Honeywell International (public, Nasdaq: HON) \u2014 Honeywell is actively splitting: Solstice Advanced Materials spun off Oct 2025, Aerospace spin-off planned for Q3 2026",
        "revenue": "Not separately disclosed (folded into Honeywell's Aerospace, Building Automation, Energy &amp; Industrial Automation segments)",
        "revenue_short": "Not disclosed",
        "offering": "Forge connects Honeywell's aerospace, building automation, process automation and industrial automation businesses into one AI-enabled operational-insight layer \u2014 conceptually close to Sand's cross-sector \u201ccontrol layer\u201d pitch.",
        "digital_twin": "Partial (asset/process monitoring, not a full physical digital twin)",
        "genai": "Emerging",
        "buyer": "Industrial, building and aerospace operations leaders",
        "customers": ["Large industrial, aerospace and building-operator accounts across Honeywell's installed base"],
        "people": [
            {"name": "Vimal Kapur", "title": "Chairman &amp; CEO, Honeywell"},
        ],
        "description": "Currently mid-breakup: Honeywell is separating into standalone Aerospace, Automation and other businesses through 2026, which makes Forge's future scope and reporting lines a live open question \u2014 but it also has the best employee sentiment of any name on this list.",
        "position_note": "Most similar to Sand in ambition \u2014 a cross-sector operational AI layer \u2014 but embedded inside a conglomerate that is actively being taken apart, adding real near-term uncertainty to the platform's trajectory.",
        "glassdoor": {"rating": "4.1", "reviews": "23,600+", "recommend": "84%", "outlook": "75%", "ceo_approval": "88%"},
        "use_cases": [
            {"sector": "Warehousing / logistics", "deployment": "U.S. retailer \u2014 Honeywell Forge Connected Warehouse / Performance+", "impact": "5 incidents resolved in 4 months, 17 hours of unplanned downtime avoided, ~$40K idle-labor savings, capacity up 150,000+ cases (~$7.5M product value)", "status": "Deployed", "source": "https://process.honeywell.com/content/dam/forge/en/documents/distribution-centers-documents/Automation_That_Delivers_CaseStudy.pdf"},
        ],
        "sentiment_bull": [
            "Highest employee Glassdoor rating on this list (4.1/5, 84% recommend, 88% CEO approval)",
            "Quantified, concrete case study results (Connected Warehouse) with clear ROI framing",
            "Cross-sector ambition \u2014 aerospace, buildings, process and industrial automation unified under one insight layer",
        ],
        "sentiment_bear": [
            "Real organizational uncertainty: Honeywell is actively splitting into separate public companies through 2026 (Aerospace spin-off, WWS and PSS sales)",
            "Forge-specific revenue, headcount and roadmap are not disclosed separately from the parent's segments",
            "AI/GenAI capability is described as \u201cemerging\u201d rather than a current core strength versus AI-native competitors",
        ],
        "customer_sentiment": "Published case studies show real, quantified operational wins, but Forge-specific third-party review coverage (G2/Gartner) is thin \u2014 most available sentiment data is at the parent Honeywell level, not the Forge product specifically.",
        "employee_sentiment": "Best overall employer sentiment on this list; some reviews flag aggressive sales quotas and bureaucracy typical of a large industrial conglomerate mid-restructuring.",
        "gip_connection": "No connection found. Honeywell serves airports and industrial operators broadly, which overlaps with GIP's transport and energy portfolios in principle, but no named GIP asset was confirmed as a Forge customer.",
        "blackrock_connection": "Confirmed passive ownership \u2014 roughly 6.6% of Honeywell, per a July 2026 filing made under the newly separate \u201cHoneywell Aerospace\u201d filing entity, reflecting Honeywell's ongoing corporate breakup into standalone businesses.",
    },
    {
        "slug": "siemens-xcelerator",
        "name": "Siemens Xcelerator",
        "website": "https://www.siemens.com/global/en/company/topic-areas/siemens-xcelerator.html",
        "linkedin": "https://www.linkedin.com/company/siemens",
        "category": "Open industrial digital-business platform / ecosystem",
        "tagline": "Open digital business platform connecting hardware, software and an IoT-enabled partner ecosystem",
        "founded": "Launched 2022 (building on a 2019 software portfolio); Siemens AG founded 1847",
        "hq": "Munich, Germany",
        "employees": "~320,000+ (Siemens AG overall; Xcelerator-specific headcount not disclosed)",
        "ownership": "Platform of Siemens AG (public, ETR: SIE)",
        "revenue": "Not separately disclosed; Siemens digital business was ~\u20ac5.6B (2021 baseline) targeting ~10% CAGR",
        "revenue_short": "Not disclosed",
        "offering": "A marketplace/ecosystem spanning Teamcenter, NX, Solid Edge and Simcenter (engineering software), Building X and Industrial Operations X (IoT/AI operations), plus a growing library of partner apps and an Industrial Copilot.",
        "digital_twin": "Yes (extensive, across design and operations)",
        "genai": "Yes (Siemens Industrial Copilot)",
        "buyer": "Industrial, buildings and mobility engineering &amp; operations leaders",
        "customers": ["Hyundai", "Kia", "Daimler Truck", "large global manufacturing &amp; infrastructure operators"],
        "people": [
            {"name": "Roland Busch", "title": "President &amp; CEO, Siemens AG"},
            {"name": "Cedrik Neike", "title": "Managing Board Member &amp; CEO, Digital Industries"},
        ],
        "description": "The broadest ecosystem on this list by design \u2014 an open marketplace of Siemens and third-party tools rather than a single unified product, backed by one of the largest industrial conglomerates in the world.",
        "position_note": "Overlaps with Sand on digital twins and cross-sector ambition, but Xcelerator is a marketplace/ecosystem strategy rather than a single deployed control-layer product.",
        "glassdoor": {"rating": "4.1", "reviews": "16,900+", "recommend": "81%", "outlook": "73%", "ceo_approval": "89%"},
        "use_cases": [
            {"sector": "Manufacturing", "deployment": "Digital-twin-based production ramp-up across Xcelerator manufacturing customers", "impact": "Up to 40% reduction in production ramp-up time (Siemens-published platform metric)", "status": "Deployed", "source": "https://www.siemens.com/global/en/company/topic-areas/siemens-xcelerator.html"},
            {"sector": "Buildings", "deployment": "Building X \u2014 campus energy &amp; operations management", "impact": "Campus operators cut utility costs by 25% per square foot (Siemens-published platform metric)", "status": "Deployed", "source": "https://www.siemens.com/global/en/company/topic-areas/siemens-xcelerator.html"},
            {"sector": "Manufacturing (automotive)", "deployment": "Hyundai, Kia, Daimler Truck \u2014 Xcelerator engineering &amp; automation tools", "impact": "100% collision-free machining trials reported across industrial Xcelerator deployments (Siemens-published platform metric)", "status": "Deployed", "source": "https://press.siemens.com/global/en/pressrelease/siemens-xcelerator-speeds-digital-transformation-and-enables-new-offerings"},
        ],
        "sentiment_bull": [
            "Strong employee sentiment (4.1/5, 81% recommend, 89% CEO approval) backed by one of the largest industrial balance sheets globally",
            "Published, quantified platform-wide outcome metrics (ramp-up time, utility costs, machining reliability)",
            "Broadest ecosystem/marketplace model \u2014 open to certified third-party hardware, software and services",
        ],
        "sentiment_bear": [
            "Xcelerator-specific revenue is never broken out from Siemens AG's overall digital business figures",
            "Marketplace/ecosystem complexity means buyers assemble multiple products rather than adopt one unified platform",
            "Platform-wide metrics (40% ramp-up reduction, etc.) are aggregate marketing figures, not single-customer audited results",
        ],
        "customer_sentiment": "Named automotive OEM customers (Hyundai, Kia, Daimler Truck) and platform-wide outcome statistics are published, but individual, quantified single-customer case studies are less prominent than for AVEVA or Bentley \u2014 sentiment is inferred more from platform-level claims than deep-dive references.",
        "employee_sentiment": "Consistently positive across a very large review base; global exposure and learning opportunities are the most-cited pros, with bureaucratic pace and slower career progression the most-cited cons.",
        "gip_connection": "No named GIP portfolio company was confirmed as a Siemens customer, though Siemens' scale across rail, energy and industrial automation plausibly overlaps with several GIP-owned assets (e.g., Pacific National and Italo rail, various energy platforms) \u2014 no specific deployment was confirmed.",
        "blackrock_connection": "Confirmed \u2014 BlackRock is Siemens AG's largest shareholder at roughly 6.5%\u20136.9% of shares outstanding across recent disclosures, ahead of Vanguard and Capital Research and Management.",
    },
]
